### ISSUE TITLE
Variavel KJUR dando erro ao importar pagarme.js como módulo

### ISSUE THREAD

**Issue by MarcoWorms** [pagarme/pagarme-js#10]
Estou usando Vue.js e a API da pagarme mas não estava conseguindo utilizar o arquivo "pagarme.js". Incluir por HTML não era uma opção então tentei baixar ele e utilizar o "import" do ES2015

`import PagarMe from '../assets/pagarme-min'`

mas mas isso disparava um erro:

`pagarme.js?0203:2012Uncaught ReferenceError: KJUR is not defined`

depois de um tempinho mexendo consegui arrumar, foi só declarar o KJUR na linha acima que deu erro:

Antes:
2012: `if (typeof KJUR == "undefined" || !KJUR) KJUR = {};`

Depois:
2012: `var KJUR;`
2013: `if (typeof KJUR == "undefined" || !KJUR) KJUR = {};`

Agora deu tudo certo 👍  mas fica a dica ai pra compatibilizar com os módulos do ES2015

**Comment by MarcoWorms** [comment]
Mentira, não deu certo, to tentando arrumar aqui pq ele não ta validando o cartão

**Comment by MarcoWorms** [comment]
Pronto, agora deu tudo certo, tinha outra linha com var não declarada:

Antes:
4378: `for (i = 0; i < luhnLess.length; i++)`

Depois:
4378: `for (var i = 0; i < luhnLess.length; i++)`

**Comment by grvcoelho** [comment]
@MarcoWorms: Sensacional! Consegue mandar um PR? :smile:

**Comment by MarcoWorms** [comment]
@grvcoelho ta ai o PR!
