### ISSUE TITLE
Erro ao criar o cartão

### ISSUE THREAD

**Issue by alutsu** [pagarme/pagarme-js#103]
## Problema
Estou tentando criar um cartão utilizando o código de exemplo [neste link](https://docs.pagar.me/reference#criando-um-cartao), para pegar o seu "card_id" porém, sempre me é retornado o código de erro 400, ou seja, está faltando um parâmetro.

## Código
```js
import pagarme from "pagarme";

pagarme.client.connect({ encryption_key: 'ENCRYPTION_KEY' })
    .then(client => client.cards.create({
      "card_number": "4018720572598048",
      "card_holder_name": "Aardvark Silva",
      "card_expiration_date": "1122",
      "card_cvv": "123",
    }))
    .then(card => console.log(card.id))
```
## Código do Erro
> ERROR Error: Uncaught (in promise): ApiError: [object Object]
> Código de Erro 400

Caso alguém tenha uma solução, de já, eu agradeço.

### Ambiente
* Firebase Hosting
* HTTPS
* Ionic 3

**Comment by flyingluscas** [comment]
Fala @alutsu, tudo bem?

Vi que você está enviando sua `encryption_key`, isso faz com que a API responda com status 400 e o seguinte erro:

``` json
"errors": [
  {
    "type": "invalid_parameter",
    "parameter_name": "api_key",
    "message": "api_key está faltando"
  }
]
```

O correto seria enviar sua `api_key`, como mostra o exemplo neste [link](https://docs.pagar.me/reference#criando-um-cartao).

Faz esse teste e me conta se funcionou okay! :)

**Comment by alutsu** [comment]
Resolvido, @flyingluscas. Eu usei a encryption key pois a documentação recomenda o uso dela no browser, mas com a api_key eu consegui criar o cartão, obrigado.

**Comment by MarcoWorms** [comment]
@alutsu Fiquei com medo agora pois aparentemente vc está usando a api key no browser. Nunca use ela no browser pois assim qualquer um pode pegar ela e fazer transações, refund, enfim, qualquer coisa que quiser na sua conta. Se vc estiver no browser NUNCA use api_key, apenas encription_key, se vc quiser criar o card faça isso do seu backend para não ter problemas de segurança com isso. Qualquer dúvida é só mandar aqui, abração!

**Comment by alutsu** [comment]
@MarcoWorms obrigado pelo alerta, bem que eu achei estranho ter que usar a API_KEY no browser, irei salvar os dados através de um backend

**Comment by MarcoWorms** [comment]
@alutsu boa! Fico feliz :D, qualquer outro problema é só abrir outra issue ou reabrir essa que a gente ve ;)
