### ISSUE TITLE
Dúvida sobre funcionamento no React Native

### ISSUE THREAD

**Issue by mmatheusmmiguel** [pagarme/pagarme-js#107]
Olá,

Gostaria de saber como funciona essa lib numa aplicação React Native, pois sempre que testo ele dá o erro: 
Unable to resolve module `url` from ...

Depois disso, eu acabei instalando a lib url e o erro foi corrigido, porém agora o erro está:
Unable to resolve module `http` from...

Alguém pode me ajudar?

**Comment by uselessdev** [comment]
Opa, boa noite @mmatheusmmiguel 

Muito obrigado por avisar, iremos dar uma olhada nisso e nos posicionamos melhor amanhã.

Eu acredito que você também pode encontrar mais informações [aqui](https://github.com/facebook/react-native/issues/11772) e [aqui](https://github.com/facebook/react-native/issues/11498)

**Comment by mmatheusmmiguel** [comment]
@uselessdev Você pode testa-lo?

**Comment by derekstavis** [comment]
Talvez você tenha que adicionar libraries de compatibilidade com o ambiente do React Native.

Eu conheço essa library aqui que deve resolver o problema: https://www.npmjs.com/package/node-libs-react-native

**Comment by mmatheusmmiguel** [comment]
@derekstavis eu só preciso fazer a instalação dessa lib junto ao pagarme ou precisa de alguma configuração?

**Comment by mmatheusmmiguel** [comment]
@derekstavis Fiz a instalação dessa lib e deu o seguinte erro: Unable to resolve module `vm` from .../node_modules/asn1.js/lib/asn1/api.js

**Comment by mmatheusmmiguel** [comment]
Olá galera, consegui utilizar essa lib do pagarme no React Native utilizando esse biblioteca: https://github.com/mvayngrib/rn-nodeify

**Comment by murilohns** [comment]
Olá @mmatheusmmiguel, seu problema foi resolvido?

Podemos fechar essa issue? =)

**Comment by mmatheusmmiguel** [comment]
@murilohns Pode sim!

**Comment by sugaith** [comment]
Olá! Estou tentando integrado o checkout do pagarme com o React Native tambem.. 
deu os mesmos erros de "Unable to resolve module url from ..." e entao instalei a biblioteca https://github.com/mvayngrib/rn-nodeify. Compilou beleza.

Porém ao usar a API com o código abaixo, me vem o erro:
`E ReactNativeJS: Can't find variable: PagarMeCheckout`

Alguma luz??

Codigo:

```
const pagarme = require('pagarme');
//tambem tentei:
// import pagarme from 'pagarme'
// e
// import pagarme from 'pagarme/browser'


abreModalPagarme() {
        // INICIAR A INSTÂNCIA DO CHECKOUT
        // declarando um callback de sucesso
        const checkout = new PagarMeCheckout.Checkout({"encryption_key":"ek_test_b6565465......876876",
            success: function(data) {
                console.log(data);
            //Tratar aqui as ações de callback do checkout, como exibição de mensagem ou envio de token para captura da transação
        }});

        // DEFINIR AS OPÇÕES
        // e abrir o modal
        // É necessário passar os valores boolean em "var params" como string
        let params = {"customerData":"false", "amount":"100000", "createToken": "true", "interestRate": 10 };
        checkout.open(params);
    }
```

**Comment by mmatheusmmiguel** [comment]
Olá @sugaith 

Você seguiu esses passos? https://github.com/mvayngrib/rn-nodeify#example-workflow

**Comment by sugaith** [comment]
Segui sim..  rodei todos os comandos, 
rodei ./node_modules/.bin/rn-nodeify --hack --install
o arquivo shim.js foi gerado, gerou os hacks certos, e compilou (ótimo). 
Porem ainda nao encontra a classe PagarMeCheckout. 

Taopouco não encontro esta classe no arquivo pagarme.js da biblioteca. instalada pelo comando:
- npm install pagarme

Tentei resolver com a lib  https://www.npmjs.com/package/node-libs-react-native também sugerida acima, porem sem sucesso (nem compila..).



Estou estudando outra abordagem.. aceitando ideias!

**Comment by sugaith** [comment]
Desculpem a minha ignorância perante esta biblioteca. 
Nao tem checkout na lib pagarme.js.. 

O pagarme.js funciona com o react-native utilizando a biblioteca [https://github.com/mvayngrib/rn-nodeify](url) 
porém não muito. 
Por exemplo:
ao usar o   metodo para validar os dados do cartao:

`const cardValidations = pagarme.validate({card: card});`          

me retorna o Erro:

```
reduce: list must be array or iterable
_reduce

...\node_modules\pagarme\pagarme.js:587:25
<unknown>
```
Outras coisas funcionam, como criar o card_hash.

_________________
Sobre o Checkout:
o Checout é disponivel apenas no script
[ https://assets.pagar.me/checkout/1.1.0/checkout.js](url)
que são mais para browsers e similares...

Tive algumas idéias "gambiarrentas" pra fazer isso funcionar no react-native:
- usar componente webview, redirecionando para uma página aonde funcione o Checkout (apenas para android)
- instalacao de NPMs que acoplam commonJS UI libs em RN (ou algo assim)
- redirecionar para uma pagina do server, abrindo o browser do celular para que funcione o processo do Checkout, e obtendo resposta via webserver de alguam forma..


 mas vendo pela documentacao creio q é melhor fazer uma interface própria para obter dados do cartão e seguir esta parte da documentação: 
[https://docs.pagar.me/docs/obtendo-os-dados-do-cartao](url)

**Comment by lhrolim** [comment]
Sei que a issue está fechada, mas hoje me deparei com o problema e como solução alteranativa apenas precisei recompilar trocando o target do webpack de node para webworker (fiz num fork meu)

Acho que seria interessante adicionar esse empacotamento.

**Comment by duduneto** [comment]
Olá meus queridos! Estou passando pelo menos problema. Sei q o Pagarme ele não tem suporte para React Native. Porém vi que vocês que passaram pelo mesmo problema conseguiram contornar esses erros Enfadonhos.
Como posso solucionar esse mesmo erro de 'Unable to resolve module'.

Não estou usando  o Checkout de pagamento, mas estou fazendo a validação dos dados do cartão e em seguida criando uma assinatura para Cobrança em Recorrência.

Aguardo uma salvação! Abraços

**Comment by rodrigoHime** [comment]
Olá pessoal, consegui colocar pra funcionar no react-native! 

No meu caso apenas queria usar para cadastrar os cartões.

- Primeiro: Crie um arquivo **pagarme.js** no seu projeto e copie 
https://github.com/pagarme/pagarme-js/blob/master/browser/pagarme.js

- Segundo: Comente a linha: https://github.com/pagarme/pagarme-js/blob/3a5bfb02f67f9c276f4c9d2eb0e88341c4769af0/browser/pagarme.js#L9457

- Terceiro: Use a lib normalmente:
```
import pagarme from '../Lib/pagarme'

pagarme.client.connect({ api_key: 'SUA_API_KEY' })
  .then(client => client.cards.create({
    card_number: '4018720572598048',
    card_holder_name: 'Aardvark Silva',
    card_expiration_date: '1122',
    card_cvv: '123',
  }))
  .then(card => console.log(card.id))
```

**Comment by yuritoledo** [comment]
@rodrigoHime você conseguiu montar o checkout do pagarme?

**Comment by rodrigoHime** [comment]
> @rodrigoHime você conseguiu montar o checkout do pagarme?

@yuritoledo Não tentei montar o checkout pois não uso no meu prejeto

**Comment by yuritoledo** [comment]
@sugaith Teve algum avanço?
Acabei caindo no mesmo empasse que você, de ter que criar uma UI para o user inserir os dados do cartão e depois fazer a request no pagarme

**Comment by sugaith** [comment]
@yuriolive sim completei o propjeto... acabou que vc nao precisa da parte do cliente pra criar hashs e td mais.. vc pode fazer absolutamente tudo pelo lado do server, passando apenas os dados mesmo pro Webserver

**Comment by sugaith** [comment]
Vejam de exemplo este protótipo:
https://github.com/sugaith/Cloud-Credit-App-with-Pagar.me

Abaixo um snippet de como usar o hash na parte do cliente.., unica coisa q funciona com nodify.
Lembrando que a melhor solução é nao usar nodify e fazer o hash pelo server (apesar disso ser uma falha de segurança).

Arquivo "TelaAddCartao.js -> insereTransacao();

![image](https://user-images.githubusercontent.com/30867558/62414707-8e44cf80-b5f5-11e9-88c0-befa96976960.png)

**Comment by yuritoledo** [comment]
Entendi, obrigado pela sua atenção!

**Comment by sugaith** [comment]
Só pra ficar completo: parte do server:

`
//COBRA CARTAO CHECKOUT...
$app->post('/pagarme/cobraCartao/', function (Request $request, Response $response) {
    $data = $request->getParsedBody();
    $user = [];
    $erro = [];
    $db = new DaoUsuario($this->db);
    //dados do user
  
    $user['nome'] = filter_var($data['nome'], FILTER_SANITIZE_STRING);

    $user['card_hash'] = $data['card_hash'];    
    $params=['api_key'=>$this->get('pagarme_prod_key'), 'card_hash'=>$user['card_hash'],
        'amount'=>$data['amount']*100, //======>>>>>>>> EM CENTAVOS!!!!!!  CUIDADO!!!!!!!!!!
//        'amount'=>100,
        "customer" => array(
            "external_id" => $data['user']['id'],
            "name" => $data['nome'],
            "document_number" => $data['cpf'],
            "email" => $data['user']['email'],
            "address" => array(
                "street" => $data['user']['logradouro'],
                "street_number" => $data['user']['complemento'],
                "neighborhood" => $data['user']['bairro'],
                "zipcode" => $data['user']['cep']
            ),
            "phone" => array(
//                "number" => $data['user']['logradouro'],
//                "ddd" => $data['user']['complemento']
                "number" => '99343541',
                "ddd" => '045'
            )
        ),
        "split_rules" => array(
            array(//do recebedor padrao 
//                "recipient_id" => "re_cj5sssssssdgvm2o2aw", //para teste
                "recipient_id" => "re_csssssssss0ikaog1", //para producao
                "percentage" => "13",
                "liable" => true,
                "charge_processing_fee" => true
            ),
            array(//do usuaro
                "recipient_id"=> $data['user']['id_pagarme_recebedor'],
                "percentage" => "87",
                "liable" => true,
                "charge_processing_fee" => true
            )
        )
    ];

    $payload = json_encode( $params );

    $ch = curl_init();
    curl_setopt( $ch, CURLOPT_URL, "https://api.pagar.me/1/transactions" );
    curl_setopt( $ch, CURLOPT_HTTPHEADER, array('Content-Type:application/json') );
    curl_setopt( $ch, CURLOPT_POST, $payload );
    curl_setopt( $ch, CURLOPT_POSTFIELDS, $payload );
    curl_setopt( $ch, CURLOPT_RETURNTRANSFER, 1);

    //FAZ A TRANSACAO!!!!
    $curl_resp = curl_exec($ch);
    curl_close($ch);

    $response->getBody()->write($curl_resp);

});
`

**Comment by euharrison** [comment]
Eu não queria instalar o rn-nodeify e precisava gerar o card_hash a partir dos dados do cartão, então criei uma webview que faz o processamento dos dados assíncrono e retorna o resultado.

No exemplo está focado apenas no método `client.security.encrypt`, mas pode ser facilmente escalado para os demais métodos.


**MyView.js**
```jsx
import React from "react";
import { Button, View } from "react-native";
import PagarMeWebView from "./PagarMeWebView";

export default class MyView {
  constructor(props) {
    super(props);
    this.pagarMeRef = React.createRef();
  }

  onPress = () => {
    if (this.pagarMeRef.current) {
      try {
        const result = await this.pagarMeRef.current.getCardHash({
          card_holder_name: 'aaa',
          card_expiration_date: '12/34',
          card_number: '4111111111111111',
          card_cvv: '333',
        });
        console.warn('CARD HASH', result);
      } catch (error) {
        console.warn('error', error);
      }
    }
  }

  render() {
    return (
      <View>
        <PagarMeWebView ref={this.pagarMeRef} />
        <Button title="Pagar" onPress={this.onPress} />
      </View>
    );
  }
}
```


**PagarMeWebView.js**
```jsx
import React from 'react';
import { StyleSheet } from 'react-native';
import { WebView } from 'react-native-webview';

export default class PagarMeWebView extends React.PureComponent {
  constructor(props) {
    super(props);
    this.state = {
      card: null,
      key: Date.now(),
    };
  }

  // public method
  getCardHash = card => {
    return new Promise((resolve, reject) => {
      this.resolve = resolve;
      this.reject = reject;

      this.setState({
        card,
        key: Date.now(), // create a unique key for each request
      });

      this.timeout = setTimeout(() => {
        this.onError('timeout');
      }, 30 * 1000);
    });
  };

  onSuccess = cardHash => {
    clearTimeout(this.timeout);
    this.timeout = null;

    if (this.resolve) {
      this.resolve(cardHash);
      this.resolve = null;
    }
  };

  onError = reason => {
    clearTimeout(this.timeout);
    this.timeout = null;

    if (this.reject) {
      this.reject(reason);
      this.reject = null;
    }
  };

  onMessage = async event => {
    const message = JSON.parse(event.nativeEvent.data);
    switch (message.type) {
      case 'success':
        this.onSuccess(message.data);
        break;
      case 'error':
        this.onError(message.error);
        break;
    }
  };

  onWebviewError = e => {
    this.onError(e.nativeEvent.description || 'webviewError');
  };

  render() {
    if (!this.state.card) {
      return null;
    }

    const cardString = JSON.stringify(this.state.card);
    return (
      <WebView
        key={this.state.key}
        originWhitelist={['*']}
        source={{
          html: `
            <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
            <script src="https://assets.pagar.me/pagarme-js/4.5/pagarme.min.js"></script>
            <script>
              function sendMessage(message) {
                window.ReactNativeWebView.postMessage(JSON.stringify(message));
              }
              pagarme.client
                .connect({ encryption_key: 'MY_ENCRYPTION_KEY_VALUE' })
                .then(client => client.security.encrypt(${cardString}))
                .then(card_hash => sendMessage({ type: "success", data: card_hash }))
                .catch(error => sendMessage({ type: "error", error: error.response || error.message || 'error' }))
            </script>
        `,
        }}
        style={styles.webview}
        onError={this.onWebviewError}
        onHttpError={this.onWebviewError}
        onMessage={this.onMessage}
      />
    );
  }
}

const styles = StyleSheet.create({
  webview: {
    position: 'absolute',
    height: 0,
    width: 0,
  },
});
```

**Comment by lucianopf** [comment]
@euharrison dúvida sincera, não seria melhor já fazer uma requisição direto pra API do Pagar.me ao invés de criar uma webview? 🤔

**Comment by euharrison** [comment]
Não quero trafegar o número do cartão de crédito pela rede, quero trafegar apenas o card_hash.

Com um card_hash é possível criar um cartão sem precisar do número do cartão em si. E para gerar um card_hash localmente precisa das libs do node etc.

**Comment by jonathangaldino** [comment]
> Não quero trafegar o número do cartão de crédito pela rede, quero trafegar apenas o card_hash.
> 
> Com um card_hash é possível criar um cartão sem precisar do número do cartão em si. E para gerar um card_hash localmente precisa das libs do node etc.

Este é um dos motivos pelo qual um suporte da pagar-me para RN seria amazing!

**Comment by jonathangaldino** [comment]
> Não quero trafegar o número do cartão de crédito pela rede, quero trafegar apenas o card_hash.
> 
> Com um card_hash é possível criar um cartão sem precisar do número do cartão em si. E para gerar um card_hash localmente precisa das libs do node etc.

Você conseguiu lidar corretamente com o webview?

**Comment by euharrison** [comment]
Estou fazendo testes nos aparelhos internos da empresa com o ambiente de teste do pagarme, até o momento está funcionando corretamente.

Para fazer a validação do número do cartão importei a lib mas só puxei o módulo de validação.
Tive que instalar o package ramda na versão 0.22.1 tb pois é utilizada internamente

```
yarn add ramda@0.22.1 && yarn add pagarme@4.5.1
```

```
import PagarMeValidations from 'pagarme/lib/validations';

PagarMeValidations({
      card: {
        card_number,
        card_expiration_date,
        card_cvv,
        card_holder_name,
      },
    })
```

**Comment by gustavolsilvano** [comment]
O pagarme funciona com Expo?

**Comment by samin** [comment]
Eu fiz assim e funcionou:
```
global.self = { fetch };
const pagarme = require('pagarme/browser');

pagarme.client.connect({ api_key: 'SUA_API_KEY' })
  .then(client => client.cards.create({
    card_number: '4018720572598048',
    card_holder_name: 'Aardvark Silva',
    card_expiration_date: '1122',
    card_cvv: '123',
  }))
  .then(card => console.log(card.id));
```

**Comment by gumiranda** [comment]
> Eu fiz assim e funcionou:
> 
> ```
> global.self = { fetch };
> const pagarme = require('pagarme/browser');
> 
> pagarme.client.connect({ api_key: 'SUA_API_KEY' })
>   .then(client => client.cards.create({
>     card_number: '4018720572598048',
>     card_holder_name: 'Aardvark Silva',
>     card_expiration_date: '1122',
>     card_cvv: '123',
>   }))
>   .then(card => console.log(card.id));
> ```

aqui deu Error: Error during encryption. Original error: Error: secure random number generation not supported by this browser
        use chrome, FireFox or Internet Explorer 11

**Comment by gumiranda** [comment]
> Eu fiz assim e funcionou:
> 
> ```
> global.self = { fetch };
> const pagarme = require('pagarme/browser');
> 
> pagarme.client.connect({ api_key: 'SUA_API_KEY' })
>   .then(client => client.cards.create({
>     card_number: '4018720572598048',
>     card_holder_name: 'Aardvark Silva',
>     card_expiration_date: '1122',
>     card_cvv: '123',
>   }))
>   .then(card => console.log(card.id));
> ```

n funciona

**Comment by bmamone** [comment]
> Eu fiz assim e funcionou:
> 
> ```
> global.self = { fetch };
> const pagarme = require('pagarme/browser');
> 
> pagarme.client.connect({ api_key: 'SUA_API_KEY' })
>   .then(client => client.cards.create({
>     card_number: '4018720572598048',
>     card_holder_name: 'Aardvark Silva',
>     card_expiration_date: '1122',
>     card_cvv: '123',
>   }))
>   .then(card => console.log(card.id));
> ```

Cuidado, acredito que não deveria estar usando sua API_KEY no frontend!

**Comment by fabianosilvait** [comment]
> 
> 
> Não quero trafegar o número do cartão de crédito pela rede, quero trafegar apenas o card_hash.
> 
> Com um card_hash é possível criar um cartão sem precisar do número do cartão em si. E para gerar um card_hash localmente precisa das libs do node etc.

Para mim esta aparecendo essa mensagem.

Error: Error during encryption. Original error: Error: secure random number generation not supported by this browser
use chrome, FireFox or Internet Explorer 11

Criar uma WebView é a unica opçao?

**Comment by jonathangaldino** [comment]
> > 
> > 
> > Não quero trafegar o número do cartão de crédito pela rede, quero trafegar apenas o card_hash.
> > 
> > Com um card_hash é possível criar um cartão sem precisar do número do cartão em si. E para gerar um card_hash localmente precisa das libs do node etc.
> 
> Para mim esta aparecendo essa mensagem.
> 
> Error: Error during encryption. Original error: Error: secure random number generation not supported by this browser
> use chrome, FireFox or Internet Explorer 11
> 
> Criar uma WebView é a unica opçao?

O @euharrison esta tendo sucesso por meio da web view. Acredito que pode ser uma opção viável. Faz um tempo que não mexo com essa api.

**Comment by tboerc** [comment]
Para quem está tendo problemas ao gerar o card_hash, mais especificamente o erro:
```
Error: Error during encryption. Original error: Error: secure random number generation not supported by this browser
use chrome, FireFox or Internet Explorer 11
```
Consegui solucionar esse problema usando esse pacote: [react-native-get-random-values](https://www.npmjs.com/package/react-native-get-random-values). Com ele a criação de hash funcionou, preciso testar ainda em outros dispositivos, mas tudo indica que deu certo.
Lembrando que estou importando do `pagarme/browser` e não direto o `pagarme`.

**Comment by fabianosilvait** [comment]
@caiqueex acho que a opção mais rápida é você criar um back-end em node.js e fazer seu app se comunicar por lá, eu acho que a pagar.me não vai dar um suporte para RN.

**Comment by gumiranda** [comment]
> alguem conseguiu arrumar/contornar esses problemas? eu estou implementando agora o pagarme no meu app React Native e to com o erro Unable to resolve module `url` from `node_modules/pagarme/pagarme.js`: url could not be found within the project...
> 
> seria perfeito um suporte pra RN do lado da pagar.me :/

esse video explica uma forma de integrar no react native https://www.youtube.com/watch?v=dP0QtPpsgYg
