### ISSUE TITLE
Promise catch problem

### ISSUE THREAD

**Issue by vinyguedess** [pagarme/pagarme-js#109]
I'm having a problem when creating a Transaction, it is triggering 'catch' on Promise but when consoling error message it returns a stringed object.
```typescript
console.log(err.message);
// Prints "[object Object]"
```

![captura de tela de 2018-01-30 18-34-06](https://user-images.githubusercontent.com/10143612/35589877-560fa1ae-05ec-11e8-93cb-a3cf4cf7b9eb.png)

**Comment by vinyguedess** [comment]
![captura de tela de 2018-01-30 18-34-06](https://user-images.githubusercontent.com/10143612/35589910-6a3c523a-05ec-11e8-9a46-20f5f163bda0.png)

**Comment by vinyguedess** [comment]
I just looked into node_modules/pagarme folder and found how to get my error message but it's being called by other functions. Hope you guys can solve it soon.
![captura de tela de 2018-01-30 18-50-42](https://user-images.githubusercontent.com/10143612/35590686-bf56c10e-05ee-11e8-9c4f-f5e6cac224f9.png)
![captura de tela de 2018-01-30 18-50-50](https://user-images.githubusercontent.com/10143612/35590687-bf75ba28-05ee-11e8-8143-f79d0e572c6f.png)

**Comment by piiih** [comment]
@vinyguedess when you get the error message like an `Object` you need to use `JSON.stringify` on the error message, so you'll can see it. ;)

**Comment by vinyguedess** [comment]
But the error doesn't come as an object. The problem is that somehow you guys don't JSON.stringify and when I try to access attribute message in Error class that was thrown it returns "[object Object]".
And I can't JSON.stringify what already is a string.

![Bash error message](https://user-images.githubusercontent.com/10143612/35589910-6a3c523a-05ec-11e8-9a46-20f5f163bda0.png)

As you can see in ApiError it comes from inside pagarme sdk as "[object Object]"

**Comment by vagnervst** [comment]
Hi @vinyguedess! I'm Vagner, from Pagar.me's Tech Support. Found some of your most recent POST requests to `/transaction` and two of them caused the following errors:

```
child \"external_id\" fails because [\"external_id\" must be a string]
```
```
"child \"country\" fails because [\"country\" with value \"BR\" fails to match the required pattern: /^[a-z]{2}$/]"}]
```

Could you retry with a lowercase "br" and passing `external_id` as a string? 

About the error message, it would be very helpful if you showed us your code (hiding any API/Encryption Key for security reasons) but the following code should work:

```javascript
pagarme.client.connect({ api_key: 'API_KEY' })
.then( client => client.transactions.create(payload))
.then( transaction => console.log(transaction) )
.catch( err => console.log(JSON.stringify(err)) )
```

**Comment by vinyguedess** [comment]
So, before my code I need to explain some things:
* We work with many payment gateways so I use interfaces and Factory pattern so I can make them all work good without problem.
* My project uses typescript
* The output is from mochajs
* So, I'm forcing an external_id as integer type so I can simulate an error:

### Piece of code
```typescript
    public createCustomer(customer:Customer):Promise<boolean>
    {
        return this.pagarme.then(client => {
            return client.customers.create({
                'name': customer.name,
                'email': customer.email,
                'external_id': customer.external_id,
                'type': customer.type,
                'country': customer.address.country.toLowerCase(),
                'birthday': customer.birthday,
                'phone_numbers': customer.phones,
                'documents': customer.documents
            })
            .then(created => {
                if (Array.isArray(customer.cards))
                    return Promise.all(
                        customer.cards.map(card => this.createCard(card, customer))
                    )
                    .then(() => true);
    
                return true;
            })
        })
        .catch(err => {
            console.log(err.message);
            console.log(JSON.stringify(err.message));
            // this.addError(err.message);
            return false;
        });
    }
```

### MochaJS Output:
![Bash MochaJS Output](https://user-images.githubusercontent.com/10143612/35632176-20d69e88-068d-11e8-916c-362f8cf3236c.png)

Both consoles I wrote on .catch are below "Creating customers"

**Comment by vinyguedess** [comment]
BTW, if I have a question about the SDK and API and didn't find that in Docs and Reference, there's a proper channel por helping or could it be here ?

**Comment by piiih** [comment]
You can send to suporte@pagar.me, but you can talk here too.
Did you try to `JSON.stringify` the `err` instead `err.mesage?

**Comment by henriquekano** [comment]
Also, in every page of the docs, there's a `suggest edits` button where you can make your changes and create "PR"s later reviewed by us  :)

**Comment by vinyguedess** [comment]
@piiih I was trying to force an error again consoling "err", and here is what I discovered, errors can be fetched by calling 'response' attribute from err object.

### Code
```typescript
    public async createCustomer(customer:Customer)
    {
        return this.pagarme.then(client => {
            return client.customers.create({
                'name': customer.name,
                'email': customer.email,
                'external_id': customer.external_id,
                'type': customer.type,
                'country': customer.address.country.toLowerCase(),
                'birthday': customer.birthday,
                'phone_numbers': customer.phones,
                'documents': customer.documents
            })
            .then(created => {
                customer.id = created.id;
                if (Array.isArray(customer.cards))
                    return Promise.all(
                        customer.cards.map(card => this.createCard(card, customer))
                    )
                    .then(() => !this.hasErrors());
    
                return true;
            })
        })
        .catch(err => {
            console.log(err.response.errors);
            // this.addError(err.message);
            return false;
        });
    }
```

### Result
![captura de tela de 2018-02-01 10-18-43](https://user-images.githubusercontent.com/10143612/35678180-844076c2-0739-11e8-8b27-b70b35999ad1.png)

If it was on purpose and should I use response attribute or you guys will make a correction about message attribute ?

**Comment by vinyguedess** [comment]
@henriquekano Thanks about the tip

**Comment by mccraveiro** [comment]
An error object should always have a "message". We definitely need to fix this on pagarme-js
