### ISSUE TITLE
Attaching transactions to a customer

### ISSUE THREAD

**Issue by vinyguedess** [pagarme/pagarme-js#110]
I already implemented customers, cards and transactions creation.
The problem is, for every transaction I create I have to send "customer" parameter on payload (cause "analise antifraude" is enabled), and API creates another customer, even if CPF, External_id and names are equally the same.

### Tryed
* Sending "id" parameter on customer
* Attach card to customer and then on transaction only send card_id
    * It partially works, because it returns true but creates another customer.
* If I remove customer parameter or send only an ID on it's value doesn't work.

**Comment by vinyguedess** [comment]
No response for me here ?

**Comment by murilohns** [comment]
@vinyguedess still need help?
