### ISSUE TITLE
Documentação

### ISSUE THREAD

**Issue by rafbgarcia** [pagarme/pagarme-js#12]
essa lib tem documentação em algum lugar?

valeu!

**Comment by MarcoWorms** [comment]
Existe referências pra ela na documentação oficial do Pagar.me

https://docs.pagar.me/capturing-card-data/#capturando-os-dados-em-uma-pagina-web

Fora isso não há outro lugar com uma documentação, ela serve para gerar o card_hash como mostrado no exemplo acima mas se vc ver o código fonte tem algumas funções de utilidades para trabalhar com cartões :)

**Comment by rafbgarcia** [comment]
show mano, valeu
