### ISSUE TITLE
Accept `apiVersion` on connect

### ISSUE THREAD

**Issue by derekstavis** [pagarme/pagarme-js#129]
## Description

When using `connect`, it would be great to accept an `apiVersion` property to set the API version for the client. 

### Current Behavior

It should be possible to use `pagarme.client.connect({ headers: 'X-PagarMe-Version': '2017-08-18', ... })`, but it looks like it isn't working.

### Expected Behavior

It should be possible to use `pagarme.client.connect({ apiVersion: '2017-08-18', ... })` to define an API version to the client.

**Comment by alalbux** [comment]
this [PR](https://github.com/pagarme/pagarme-js/pull/155) partially solves this problem

**Comment by otaviopace** [comment]
I think it actually solves the problem, just in another way.
In my opinion this Issue should be closed.
