### ISSUE TITLE
Register package on NPM

### ISSUE THREAD

**Issue by rafaelcamargo** [pagarme/pagarme-js#13]
Is it already registered on NPM? I could not find it.
For a better controlling dependencies, register this package on NPM. Doing so, that dependency becomes clear and together all other ones in `package.json`.

**Comment by felquis** [comment]
Thank you @rafaelcamargo, we will update it as soon as possible.

**Comment by felquis** [comment]
For now you need to install from github 

```
{
  "dependencies": {
    "pagarme-js": "pagarme/pagarme-js#2.2.1"
  }
}
```

`#2.2.1` is the latest tag right now, checkout a newer on [releases page](https://github.com/pagarme/pagarme-js/releases)

Closing it for now, re-open if you have any trouble 💸

**Comment by Madalosso** [comment]
@felquis I tried to add this dependency but npm complains about "ambiguous argument '2.2.1'"...
Then I tried to add the 'v' from the tag used to the last release and looks like the dependency is solved.
```
{
  "dependencies": {
    "pagarme-js": "pagarme/pagarme-js#v2.2.1"
  }
}
```

@rafaelcamargo Did you manage to get it without the "v" in the dependency?

**Comment by rafaelcamargo** [comment]
Just `checkout.js` was necessary for me at that time, so I have included it on my index via `<script>` and that's it.
