### ISSUE TITLE
Problemas com a biblioteca de checkout 

### ISSUE THREAD

**Issue by felipe-gdr** [pagarme/pagarme-js#130]
A modalidade de checkout está com algum problema? Não estou conseguindo rodar nem localmente e nem no [exemplo que vocês tem no CodePen](https://codepen.io/pagarme/pen/YrgeLP?editors=1111).

Parece que todos os resources são baixados, a markup é adicionada ao DOM (iframe com vários elementos dentro), mas nada está visível.

**Comment by murilohns** [comment]
fala @felipe-gdr , tudo bem?

Não temos esse problema mapeado no checkout atualmente, você pode enviar um gif ou um vídeo para que possamos entender melhor o problema?

**Comment by felipe-gdr** [comment]
Beleza, @murilohns !

Agora não estou conseguindo reproduzir o comportamento, nem no CodePen, nem na minha máquina. 🤷‍♂️ 

Vou fechar esse issue, e ficar de olho. Se ocorrer novamente, reabro com mais evidências.

Valeu!
