### ISSUE TITLE
Recebedor e Conta Bancaria.

### ISSUE THREAD

**Issue by lucazin** [pagarme/pagarme-js#131]
Bom dia!

Tem como apagar uma conta bancaria ou modificar ?
contudo também tem como apagar um recebedor ?

Infelizmente criei alguns recebedores na api de testes e nao consigo apagar.

**Comment by murilohns** [comment]
Olá @lucazin, nada pode ser apagado da API do Pagar.me.

Caso você não queira mais utilizar um recebedor, você deve criar outro para utilizar em seu lugar.

**Comment by lucazin** [comment]
Certo, mas alterar o nome tambem nao ? 
Se por exemplo o meu recebedor alterou a conta bancaria dele.. eu tenho que criar outra conta bancaria ? nao posso atualizar a mesma

**Comment by murilohns** [comment]
@lucazin, você pode [atualizar um recebedor](https://docs.pagar.me/v2017-08-28/reference#atualizando-um-recebedor), mas apenas a conta bancária dele.

A nova conta bancária dele deve possuir o mesmo número de documento que a conta bancária atual.

**Comment by lucazin** [comment]
Pelo c# eu consigo tambem ?

Em sex, 10 de ago de 2018 às 09:43, Murilo Henrique Nascimento Souza <
notifications@github.com> escreveu:

**Comment by murilohns** [comment]
Olá @lucazin, sim, com todas a SDK's você consegue fazer isso.

**Comment by lucazin** [comment]
Ola Murilo.
Obrigado!

Quando eu mudar pra chave de producao, os testes que eu fiz vao sumir no
dashboard correto ?

Em sex, 10 de ago de 2018 às 15:28, Murilo Henrique Nascimento Souza <
notifications@github.com> escreveu:

**Comment by murilohns** [comment]
Olá @lucazin, o Pagar.em trabalha com ambientes separados, tudo o que você fizer em ambiente de produção não terá ligação nenhuma com o ambiente de testes. Até mesmo a visualização na dashboard é separada, ou seja, ao selecionar "Visualizar Operação", você só verá os dados do ambiente de produção =)

Se tiver dúvida em mais algo fico à disposição.

**Comment by lucazin** [comment]
Murilo! Muito obrigado pela atencao !
Ta sendo de grande valia seu suporte como um todo.

Tenho algumas duvidas relacionado a antecipacao como funciona... se o meu
recebedor quiser antecipar.. eu q tenho q informar o saldo pra ele ? Ele
consegue antrcipar sozinho ou depende d mim ?

No dash de testes eu n consigo antecipar nada.. tenho la a receber xxxxxx
mas diz q esse recebedor n pode antecipar.

Mas como funciona a antecipacao ?
Com relacao as taxas vi que a taxa e de 5% aqui.no painel de testes
..quando for pra.producao..tem.como negociar essas taxas de acordo com meu
negócio?

Realizei o split de 100 reais.. ahh..
Entao eu como marketplace na hora do split eu tenho que informar os 2
recebedores...eu e o meu vendedor ?  Ele n identifica que ja sou eu a
company ..? E assim so identificando o recebedor x ? Pq.vou dividir o
dinheiro entre o marketplace e o recebedor... tenho q colocar as 2 contas ?

Obrigado!

Em Seg, 13 de ago de 2018 09:09, Murilo Henrique Nascimento Souza <
notifications@github.com> escreveu:

**Comment by murilohns** [comment]
fala @lucazin ,

>  Tenho algumas duvidas relacionado a antecipacao como funciona... se o meu recebedor quiser antecipar.. eu q tenho q informar o saldo pra ele ? Ele consegue antrcipar sozinho ou depende d mim ? No dash de testes eu n consigo antecipar nada.. tenho la a receber xxxxxx mas diz q esse recebedor n pode antecipar. Mas como funciona a antecipacao ? Com relacao as taxas vi que a taxa e de 5% aqui.no painel de testes ..quando for pra.producao..tem.como negociar essas taxas de acordo com meu negócio? 

Ele sempre dependerá de você para [antecipar](https://docs.pagar.me/v2017-08-28/reference#criando-uma-antecipa%C3%A7%C3%A3o), pois a antecipação é feita através da API Key. O que você pode é criar uma tela em sua aplicação, parecida com a dashboard do Pagar.me, exibindo o [saldo de seu recebedor](https://docs.pagar.me/v2017-08-28/reference#saldo-de-um-recebedor). Assim ele saberá quanto tem à receber. Após isso, basta criar a antecipação para o recebedor com o valor que ele selecionar.

> Mas como funciona a antecipacao ? Com relacao as taxas vi que a taxa e de 5% aqui.no painel de testes ..quando for pra.producao..tem.como negociar essas taxas de acordo com meu negócio? 

Sim, é possível negociar isso quando estiver em contato com o time comercial Pagar.me.

> Realizei o split de 100 reais.. ahh.. Entao eu como marketplace na hora do split eu tenho que informar os 2 recebedores...eu e o meu vendedor ? Ele n identifica que ja sou eu a company ..? E assim so identificando o recebedor x ? Pq.vou dividir o dinheiro entre o marketplace e o recebedor... tenho q colocar as 2 contas ?

Sim, todos recebedores que receberão alguma parte do dinheiro da transação devem ser informados, mesmo que essa parte seja referente ao recebedor principal de sua conta.

**Comment by lucazin** [comment]
Legal Murilo!

Em breve vou estar conversando com o time comercial, provavelmente terei um
grande volume de vendas.

Uma duvida, é possivel personalizar o nome que vai na fatura via api ?

Em seg, 13 de ago de 2018 às 09:25, Murilo Henrique Nascimento Souza <
notifications@github.com> escreveu:

**Comment by lucazin** [comment]
Obrigado parceiro..!

Em Ter, 14 de ago de 2018 09:24, Murilo Henrique Nascimento Souza <
notifications@github.com> escreveu:

**Comment by lucazin** [comment]
Boa tarde Murilo.. esta tudo certo com a api de testes?

Nao alterei nada e parou de funcionar o split de pagamentos pra mim,  antes
funcionava normal.. fui fazer uma transacao e recebi uma exception

[image: erropagarme1.png]

Estava funcionando normal e agora parou, estou fazendo assim

  transaction.SplitRules = new[]
                     {
                         new SplitRule
                        {
                             Recipient = RecebedorID,
                             Percentage = 97,
                             ChargeProcessingFee = true,
                             Liable = true
                        },
                       new SplitRule
                       {
                             Recipient = Principal_ID,
                             Percentage = 3,
                             ChargeProcessingFee = false,
                             Liable = false
                       }
                    };

O que pode estar acontecendo ?


Em ter, 14 de ago de 2018 às 09:28, Lucas Bergamo <bergamo86@gmail.com>
escreveu:

**Comment by lucazin** [comment]
http://status.pagar.me/   Erro 500 tambem.

Em qua, 15 de ago de 2018 às 14:41, Lucas Bergamo <bergamo86@gmail.com>
escreveu:
