### ISSUE TITLE
Recebedores e amount

### ISSUE THREAD

**Issue by juliobetta** [pagarme/pagarme-js#132]
Olá pessoal,
Estou criando um marketplace de venda de alimentos, no qual o cliente poderá adicionar produtos de diversos parceiros em seus pedidos. 

Na finalização do pedido, eu exibo o checkout transparente e capturo a transação no servidor, passando as regras de split como parâmetro. Cada recebedor do split deveria receber o valor total da compra de seus produtos + frete, menos a porcentagem retida pelo administrador do marketplace. 

    import pagarme from 'pagarme'

    const PARTNER_SHARE = 0.9;

    pagarme.client.connect({ api_key: 'SUA_API_KEY' })
      .then(client => client.transactions.capture({
        id: 1399451,
        amount: 800,
        split_rules: [
          {
            recipient_id: 're_ciyoloogb0100l46dy6f1iuww',
            liable: 'true',
            charge_processing_fee: 'true',
            amount: 550 * PARTNER_SHARE
          },
          {
            recipient_id: 're_ciyoloogb0100l46dy6f1iuww',
            liable: 'true',
            charge_processing_fee: 'true',
            amount: 250 * PARTNER_SHARE
         }
        ]
      }))

Neste caso eu faço o cálculo e passo este valor (em centavos) na propriedade ```amount```. Porém, o pagarme nao permite que a soma do  ```amount``` dos recebedores seja diferente do ```amount``` da transação em si. 

    [
      {
        "type": "invalid_parameter",
        "parameter_name": "split_rules",
        "message":"O valor total do split deve ser igual ao valor da transação."
      }
    ]

Como eu faria para repassar uma parte de cada split para o administrador do marketplace? Criando um ```recipient```? 🤔

Obrigado desde já.

**Comment by murilohns** [comment]
Olá @juliobetta, tudo bem?

Se o dinheiro for liquidado na mesma conta bancária que foi cadastrada no Pagar.me, você pode recuperar o recebedor principal da conta [nessa rota](https://api.pagar.me/1/company?API_KEY=SUA_CHAVE_DE_API). Existirá um campo chamado `default_recipient_id`, que pode ser utilizado como terceiro parâmetro da split.

Outra alternativa é [criar um novo recebedor](https://docs.pagar.me/v2017-08-28/reference#criando-um-recebedor) para o _marketplace_, e enviá-lo na regra de split.

O ponto é que, como o dinheiro será liquidado em 3 contas diferentes, você deve passar 3 recebedores na regra de split, e a soma do `amount` dessas regras deve ter o mesmo valor que o `amount` da transação.

**Comment by juliobetta** [comment]
Legal @murilohns !!! Vou utilizar o ```recipient_id``` da conta cadastrada então! 

Muito obrigado pela atenção.
