### ISSUE TITLE
Filtro no javascript

### ISSUE THREAD

**Issue by estevaosa** [pagarme/pagarme-js#136]
Olá pessoal, tudo bem?

Estou tentando fazer alguns filtros, porem, sem sucesso. Gostaria de fazer filtro entre datas, veja abaixo:

.then(client => client.transactions.find({
			  customer:{id:"+id+"},
			  count:1000000,
			  date_created:">="+data_inicial_mili+"",
			 // date_created:"=<="+data_final_mili+""
			
		  }))

Não consigo colocar duas datas, como fazer isso usando o js?

Outro item: Gostaria de trazer todas as transações, para isso coloquei o count bastante alto. No php eu colocava count=0 e retornava todas as transações, por aqui parece ser diferente. 

Sobre o count eu também consigo buscar por intervalos, exemplo:
Transações de 1 à 10, depois uma nova consulta com transações de 11 à 20 e assim por diante.

Obrigado

**Comment by otaviopace** [comment]
Olá @estevaosa ! Consegue mostrar o exemplo que utiliza em PHP? Estou tentando ver aqui qual é a melhor forma de se buscar essas transações em um alcance de data :slightly_smiling_face:

**Comment by estevaosa** [comment]
Olá @otaviopace. Cara, na verdade eu uso o curl do PHP e chamo o end point..seria algo assim:

$url = 'https://api.pagar.me/1/transactions?api_key='.$api_usada.&date_created[]=>'.$data_inicial.'&date_created[]=<'.$data_final.'&count=100000';
	

	$ch = curl_init();
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);

	curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
	

	curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0); 
	curl_setopt($ch, CURLOPT_URL, $url);


	$response = curl_exec($ch);
	echo ($response);

Abs
