### ISSUE TITLE
Não consigo filtrar assinaturas

### ISSUE THREAD

**Issue by luisrudge** [pagarme/pagarme-js#140]
## Description
Não consigo filtrar assinaturas por clientes nem por planos. Isso é relacionado a API e não ao pagarme-js em si, mas não tenho outra maneira de entrar em contato com o suporte.

#### Listando todas as assinaturas
```curl
➜  ~ curl -s -X GET https://api.pagar.me/1/subscriptions -H 'content-type: application/json' -d '{
    "api_key": "'"$APIKEY"'",
    "count": "2",
    "page": "1"
}' | jq '.[].customer.id'
751131
751122
```

#### Filtrando por id do cliente
```curl
➜  ~ curl -s -X GET https://api.pagar.me/1/subscriptions -H 'content-type: application/json' -d '{
    "api_key": "'"$APIKEY"'",
    "count": "2",
    "page": "1",
    "customer_id": "751131"
}' | jq
[]
```

## My Setup
- [x] I have tested with the latest version
- [x] I can simulate the issue easily

### Current Behavior
Não traz nenhuma assinatura quando uso um filtro por customer_id ou plan_id

### Expected Behavior
Trazer todas as assinaturas do cliente ou do plano

**Comment by murilohns** [comment]
fala @luisrudge , tudo bem?

Você deve usar elastic search para fazer essa busca.

No caso de buscar uma assinatura pelo ID do customer, você pode usar esse código:

```bash
curl -X GET https://api.pagar.me/1/search
     -d 'api_key=SUA_API_KEY' \
     -d 'type=subscription' \
     -d 'query=
     {
       "query": {
         "filtered": {
           "query":{"match_phrase":{"customer.id":{"query":"751131"}}}
         }
       }
     }'
```

O mesmo serve para planos, basta trocar `customer` por `plan` e o valor da `query`

Você pode ver mais exemplos de como usar o elastic search [aqui](https://github.com/pagarme/pagarme-pocs/tree/master/ElasticSearch%20-%20POCs)

**Comment by luisrudge** [comment]
@murilohns  A documentação aqui está errada então? https://docs.pagar.me/reference#retornando-assinaturas

**Comment by luisrudge** [comment]
ping @murilohns

**Comment by murilohns** [comment]
Fala @luisrudge,

Não necessariamente. Segundo nosso código, os campos de escritos nessa página deveriam funcionar no filtro de _querystring_.

Alguns campos não funcionam devido à caracteres especiais, por exemplo: e-mail.

Te enviei a solução com _elasticsearch_ pois é certeza que ela funcionará, tanto no filtro por e-mail, ou por propriedades de objetos (ex: customer.id, plan.id, plan.name).

**Comment by luisrudge** [comment]
@murilohns entendo que a solução do ES funciona (ainda não testei), mas o que está documentado não tá funcionando. Te mandei os comandos que estou rodando e o filtro por customer_id não retorna nada.

**Comment by luisrudge** [comment]
@murilohns ping 😬

**Comment by murilohns** [comment]
fala @luisrudge, beleza?

De fato, a documentação está errada quanto à isso.

Peço desculpas, e em breve ela será corrigida.

**Comment by luisrudge** [comment]
@murilohns tranquilo. só pra confirmar, então: a api de assinaturas não aceita filtros, é isso?

**Comment by murilohns** [comment]
Aceita sim!

Só os filtros por objetos não funcionam via _querystring_. Por exemplo, se você filtrar por `payment_method=boleto`, ela filtrará corretamente. Mas se você tentar filtrar por `plan_id`, `customer_id`, ou `card_id`, o filtro não funcionará.
Nestes casos você deve utilizar ElasticSearch pra fazer o filtro.

**Comment by luisrudge** [comment]
@murilohns perfeito! valeu por esclarecer 🎉
