### ISSUE TITLE
Erro 400 na rota https://api.pagar.me/1/subscriptions/${SubscriptId}/settle_charge

### ISSUE THREAD

**Issue by rodrigobrando** [pagarme/pagarme-js#146]
Estou tendo dificuldade em pular um pagamento em assinaturas, a resposta que obtenho é apenas um Bad Request, status 400. Segue abaixo meu código:

`async settleCharger(SubscriptId, charges) {
    try {
      const config = {
        headers: { 'content-type': 'application/json' },
      };

      const data = JSON.stringify({
        api_key: apiKey,
        charges,
      });

      const response = await axios.post(
        `https://api.pagar.me/1/subscriptions/${SubscriptId}/settle_charge`,
        data,
        config,
      );
      return response;
    } catch (error) {
      console.log(error);
    }
  },`

**Comment by murilohns** [comment]
Olá @rodrigobrando, tudo bem?

O parâmetro charges, quando enviado, deve ser um `array`, representado pelos períodos que você deseja perdoar.

Por exemplo, caso queira perdoar o `1º mês` e `3º mês`, o valor enviado deve ser `[1, 3]`

Caso queira perdoar apenas a próxima cobrança, não é necessário enviar o parâmetro `charges`.

**Comment by rodrigobrando** [comment]
OK valew @murilohns!
