### ISSUE TITLE
CVV de 4 digitos não validado

### ISSUE THREAD

**Issue by irwingmax** [pagarme/pagarme-js#147]
## Description
Cliente reportou que ao validar o cvv de 4 digitos, retorna false. Fiz o teste local e tive o mesmo retorno

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

### Current Behavior
![image](https://user-images.githubusercontent.com/38294104/49101483-71355100-f25d-11e8-9705-bc278bce2413.png)

### Expected Behavior
Validar o cvv com 4 digitos.

**Comment by murilohns** [comment]
Para que o CVV seja validado com 4 digitos, o cartão de crédito deve possuir bandeira amex.
