### ISSUE TITLE
Criar transação com card hash

### ISSUE THREAD

**Issue by yuritoledo** [pagarme/pagarme-js#153]
Apenas uma dúvida.

É possível fazer uma transação, utilizando o card_hash, ao invés dos dados do cartão do cliente?
Pois estou usando o checkout (aquele modal daora) para inserir os dados do cliente e ele me retorna o hash. Gostaria de poder fazer uma transação com ele, sem ter que obter os dados do cartão do cliente na minha aplicação.

Obrigado desde já :)

**Comment by yuritoledo** [comment]
Solved :D

**Comment by krugio** [comment]
Olá Yuri tudo bem!?
Estou com a mesma dúvida, como vc fez!?
poderia me ajudar!?

**Comment by bonattogabriel** [comment]
Olá!
Também estou com essa dúvida, como foi feito?
Tentei fazer a transação pelo backend da Aplicação utilizando apenas o card_hash porém sem sucesso.

**Comment by yuritoledo** [comment]
> Olá Yuri tudo bem!?
> Estou com a mesma dúvida, como vc fez!?
> poderia me ajudar!?

@krugio fiz com pagamento recorrente, foi assim:

```js
  const subscription = {
    payment_method: 'credit_card',
    plan_id: plan_id,
    card_hash: card_hash,
    customer: {
      name: user.name,
      email: user.contact.email
    }
  }
  const pagarme = await pagarmeConnect()
  pagarme.subscriptions.create(subscription)
```

o hash vem do `new PagarMeCheckout.Checkout()`

**Comment by krugio** [comment]
Obrigado!!

Em ter., 2 de fev. de 2021 às 19:41, Yuri Toledo <notifications@github.com>
escreveu:
