### ISSUE TITLE
Erro `api_key está faltando` quando utilizando apenas `encryption_key` no browser

### ISSUE THREAD

**Issue by luccasmaso** [pagarme/pagarme-js#17]
```
import pagarme from 'pagarme'

const card = {
  card_number: '4111111111111111',
  card_holder_name: 'abc',
  card_expiration_date: '1225',
  card_cvv: '123',
}

pagarme.client.connect({ encryption_key: 'ek_test_y7jk294ynbzf93' })
  .then(client => client.security.encrypt(card))
  .then(card_hash => console.log(card_hash))
```

![image](https://cloud.githubusercontent.com/assets/1427231/24532771/4802b3ec-1599-11e7-8bcf-07892e38a431.png)

**Comment by MarcoWorms** [comment]
Obrigado! Vamos arrumar isso agora. :)

**Comment by MarcoWorms** [comment]
Identificamos o problema aqui. Acontece que a rota que estamos usando pra validar a api_key não é válida pra encryption_key, também acabamos deixando esse teste passar D:

Obrigado por apontar, a gente vai trocar a rota de validação aqui para uma que aceita tanto encryption quanto api key e ja ja deploiaremos :)

**Comment by MarcoWorms** [comment]
Eae cara!

Então, eu resolvi o problema nessa branch aqui https://github.com/pagarme/pagarme-js/tree/fix-credentials-validation mas não gostamos de como o código ficou e queremos refatorar isso. Esse código esta fazendo um uso ruim da nossa pattern de strategies. Como agora está um pouco tarde, amanhã eu priorizarei esse refactor para ja fazermos a release da próxima versão com suas duas issues arrumada :D

Valeu, boa noite!

**Comment by MarcoWorms** [comment]
Acabei me empolgando aqui e corrigi e refatorei ja :) https://github.com/pagarme/pagarme-js/pull/20

**Comment by luccasmaso** [comment]
Massa! Vou testar aqui

**Comment by luccasmaso** [comment]
Vocês vão atualizar lá no npm pra versão 3.0.1 em breve?

**Comment by MarcoWorms** [comment]
Sim! A gente ia deployar na sexta, mas como iriamos viajar pra um lugar sem internet prefirimos deixar o deploy pra segunda. Amanhã ja colocaremos no ar a versão arrumada :)

**Comment by derekstavis** [comment]
Lancada a versão 3.0.1 @luccasmaso! Obrigado pelo report!!
