### ISSUE TITLE
Postback

### ISSUE THREAD

**Issue by souzajr** [pagarme/pagarme-js#170]
Olá,

Tenho uma dúvida bem simples sobre postback, fiquei um pouco confuso com a documentação.
Utilizando a última versão do express, essa seria a forma correta de validar um postback?

        const signature = pagarme.postback.calculateSignature(req.headers['x-hub-signature'], req.body)
        const verify = pagarme.postback.verifySignature(req.headers['x-hub-signature'], req.body, signature)

        if(verify) {
            // postback é válido
        } else {
            // postback não é válido
        }

**Comment by jonatasmaxi** [comment]
Olá @souzajr, como vai?

Meu nome é Jonatas e faço parte da equipe de suporte técnico do Pagar.me.

No calculateSignature, você precisa passar a sua api_key no primeiro parâmetro, a intenção desse método é produzir uma assinatura para que seja comparada diretamente com o header enviado na request. 

Você pode fazer a validação apenas dessa forma:  

    const verify = pagarme.postback.verifySignature(api_key, req.body, req.headers['x-hub-signature'])

Qualquer dúvida estou por aqui.

**Comment by souzajr** [comment]
Legal, muito obrigado!

**Comment by souzajr** [comment]
@jonatasmaxi, voltei. Infelizmente, não consegui resolver o problema.

Testei do jeito que você falou e deu o seguinte erro: 
![Capturar](https://user-images.githubusercontent.com/43734512/59796705-723ed600-92b4-11e9-803a-a9e4667c3fe3.PNG)


Então fiz o seguinte (adicionei o JSON.stringify() no req.body):
```
if(pagarme.postback.verifySignature(api_key, JSON.stringify(req.body), req.headers['x-hub-signature'])) {
        // postback é válido
} else {
        // postback inválido
}
```

Evitou o erro acima, porém sempre caio na opção de postback inválido. Consegue me dizer onde eu estou errando? Lembrando que estou na versão de testes, especificamente testando a confirmação de pagamento de boletos.

Obrigado!

**Comment by murilohns** [comment]
Olá @souzajr, tudo bem?

Invés de utilizar o `JSON.stringify(req.body)` para fazer a validação, utilize a biblioteca qs, pois ela faz o parse do objeto de forma identica ao Pagar.me. Assim a validação deverá funcionar.

Segue um exemplo de validação de postback:

```js

const validatePostback = (req, res, next) => {
  const apiKey = 'SUA_API_KEY'
  const verifyBody = qs.stringify(req.body)
  const signature = req.headers['x-hub-signature'].replace('sha1=', '')

  if (!pagarme
    .postback
    .verifySignature(apiKey, verifyBody, signature)
  ) {
    return res.json({error: 'Invalid Postback'})
  }

  return res.json({message: 'postback válido'})
}
```

**Comment by souzajr** [comment]
Funcionou perfeitamente. Muito obrigado!

**Comment by hoomersinpsom** [comment]
Olá, seria legal tb colocar esse exemplo na documentação https://docs.pagar.me/docs/gerenciando-postbacks

**Comment by JonhnyDev** [comment]
Tem que colocar o exemplo na documentação gente... seguindo a doc não funciona só com o exemplo do @murilohns funcionou.

**Comment by souzajr** [comment]
> Tem que colocar o exemplo na documentação gente... seguindo a doc não funciona só com o exemplo do @murilohns funcionou.

Verdade. Lembro que quebrei bastante a cabeça na época e essa é uma parte delicada de segurança, não dá pra ficar sem. Não custaria nada ter esse exemplo de validação na doc, pelo contrário. Fica de recomendação, pessoal.

**Comment by DaeltonDias** [comment]
Muito obrigado @murilohns  pelo seu código de exemplo... passei pela mesma dúvida e problema que os demais aqui dessa postagem. Sua ajuda foi excelente! Seu código funcionou aqui pra mim! Me fez economizar tempo debugando / dando console.log e testando para entender qual a maneira correta de realizar esse procedimento.

Mais uma vez muito obrigado!

PS: favor, pessoal da equipe de suporte do Pagar.me, adicionem esse código de exemplo na documentação pois o Node.js é uma linguagem muito utilizada dentro das grandes corporações e quando encontramos exemplos para tal na documentação ajuda bastante a entender.

**Comment by kazordoon** [comment]
Olá, estou usando a `API_KEY de testes` e usando o código citado acima aparenta não funcionar corretamente:

```javascript
const API_KEY = '<api_key_de_teste>';
const signature = req.headers['x-hub-signature']?.replace('sha1=', '');

const stringifiedPostback = qs.stringify(req.body);
const isValid = pagarme.postback.verifySignature(
  API_KEY,
  stringifiedPostback,
  signature,
);

console.log(isValid); // false
```

Estou usando a seguinte versão: `pagarme@^4.19.2`
