### ISSUE TITLE
Customer - Atualizar email e/ou phones

### ISSUE THREAD

**Issue by wskoderbr** [pagarme/pagarme-js#171]
## Description
Estou implementando gestao de clientes e cartoes para 1clickBuy.
Consigo criar o customer, adicinoar o cartao e utiliza-los em transacoes sem problema.
O que nao achei na documentacao foi como atulizar um registro de cliente, alterando por exemplo o email e/ou telefones do mesmo.

Utilizando o metodo create, passando o id retornado anteriormente, eh desconsiderado e criado um novo customer.

Como proceder?

## My Setup
- [X ] I have tested with the latest version
- [ X] I can simulate the issue easily

### Current Behavior
Nao ha metodo de alteração de dados de customer

### Expected Behavior
Possibilidade de alteracao dos dados do customer

**Comment by lucianopf** [comment]
Ótimo ponto @wskoderbr , realmente não está documentado nem na lib nem na referência da API, mas fazendo uns testes diretamente na API eu consegui fazer um `PUT` em `https://api.pagar.me/1/customers/<custumer_id>` alterando por exemplo o nome de um customer.

Vou buscar a razão disso não estar documentado nem implementado aqui, mas pode ter relação com a versão da API e consequentemente a escolha de não confundir os usuários.

De qualquer forma, como solução paliativa é possível fazer uma requisição direta a API para alterar esses dados. 😬

**Comment by wskoderbr** [comment]
Opa. Muito obrigado. 

Vou tentar implementar na própria api. se funcionar faço um pull request

Aproveitando tem outra duvida: [Transaction Create - Usar somente o customer_id](https://github.com/pagarme/pagarme-js/issues/174)

**Comment by nythrox** [comment]
Opa pessoal. Algum progresso nisso? Minha aplicação tem o caso de uso de atualizar o número telefone, mas na documentação não mostra se é possivel fazer isso.
