### ISSUE TITLE
Módulo pagarme/browser com referência incorreta  

### ISSUE THREAD

**Issue by luccasmaso** [pagarme/pagarme-js#18]
`index.js` está fazendo require de um arquivo que não existe. Deveria ser `module.exports = require('./pagarme.min.js')` ao invés de `module.exports = require('./pagarme.js')` para funcionar aqui.

<img width="400" alt="screenshot 2017-03-30 22 37 45" src="https://cloud.githubusercontent.com/assets/1427231/24532800/9f558f98-1599-11e7-87bd-6d9256a9bd22.png">

**Comment by MarcoWorms** [comment]
Obrigado! Vamos arrumar ainda hoje ;)

**Comment by derekstavis** [comment]
Criei o pull request #19 com o fix! Havia esquecido de adicionar essa build! Obrigado!
