### ISSUE TITLE
Integração com react-native

### ISSUE THREAD

**Issue by yuritoledo** [pagarme/pagarme-js#181]
Boa tarde senhores,

Existe alguma documentação sobre como integrar o pagarme com react-native?

Fico no aguardo, valeu!

**Comment by otaviopace** [comment]
Olá @yuritoledo ! Não temos atualmente uma documentação de como integrar no react-native, porém, como já tiveram pessoas que tentaram fazer isso, talvez consiga aprender algo com elas 🙂 

Aqui tem uma issue com uma discussão no assunto: https://github.com/pagarme/pagarme-js/issues/107

**Comment by yuritoledo** [comment]
Obrigado :)

**Comment by gumiranda** [comment]
Recomendo o canal do Dev Doido. Ele fez integraçao node e react native
