### ISSUE TITLE
Error on Ionic 2

### ISSUE THREAD

**Issue by vladiusdf** [pagarme/pagarme-js#22]
Utilizando o código de exemplo desta nova api, somente consigo fazer a geração de hash quando estou em um navegador ou simulando um navegador no celular.

Quando tento chamar da aplicação recebo a seguinte mensagem: "Error: You must suply a valid key",
E apesar de está mensagem vir da chamada de connect, pelo retorno do serviço é retornando as informações corretamente. Porém como gera erro ele não chama o meu código de geração de Hash.

Código tal qual estou usando, estou usando tanto a chave quanto a encryption por que se não colocar a chave ele dá erro.

Obs: parece ser um erro Cors.

pagarme.client.connect({ api_key : '<api_key>', encryption_key : 'e_key'})
  .then(
    client => { client.security.encrypt(card).then(card_hash => {
        this.alertCtrl.create(
          {
            title: 'foi',
            subTitle: card_hash,
            buttons: ['OK']
          }
        ).present();
        console.log(card_hash)

      },error => {
        console.log('Error ao gerar hash');
        console.log(error);

        this.alertCtrl.create(
          {
            title: 'Erro',
            subTitle: error,
            buttons: ['OK']
          }
        ).present();
      });
    },
    error => {
      console.log('Error ao autenticar');
      console.log(error);
      this.alertCtrl.create(
        {
          title: 'Erro',
          subTitle: error,
          buttons: ['OK']
        }
      ).present();
    }
  );

**Comment by MarcoWorms** [comment]
Olá! Nós corrigimos esse problema no PR #21 :)

Segunda feira nós faremos o deploy da nova versão

**Comment by derekstavis** [comment]
Olá @vladiusdf! Lancei a versão 3.0.1 no NPM. A partir de agora este problema deve estar resolvido! Qualquer coisa, pode reabrir a issue ou abrir novas issues :+1:
