### ISSUE TITLE
Problemas com setup inicial da api

### ISSUE THREAD

**Issue by gcmatheusj** [pagarme/pagarme-js#229]
## Description
Olá pessoal, hoje iniciei alguns testes com a api de pagamento do Pagar Me. Criei e confirmei minha conta, fiz a instalaçao do package para JS usando `yarn add pagarme` e fiz o a transação de teste como é proposto na documentação, porém estou recebendo um erro de api.

## My Setup
- Operating System: Ubuntu 18.04
- Project Version: 1.0.0

- [ ] I have tested with the latest version
- [ ] I can simulate the issue easily

### Current Behavior

`(node:17855) UnhandledPromiseRejectionWarning: ApiError: Pagar.me API error. Check error's "response" property for more details.`

### Expected Behavior
Deveria fazer a transação de teste normalmente

**Comment by murilohns** [comment]
Olá @gcmatheusj, não sei exatamente como você está fazendo, mas você pode verificar o que está acontecendo dessa maneira:
```js
// async/await

try {
  await pagarme.transactions.create(payload)
} catch (e) {
  console.log(e.response)
}

// Promise chain
pagarme.transactions.create(payload)
  .catch(e => console.log(e.response))
```

**Comment by gcmatheusj** [comment]
Opa, @murilohns eu fiz exatamente isso

**Comment by lucianopf** [comment]
> Opa, @murilohns eu fiz exatamente isso

Qual o resultado logado no console do `catch` @gcmatheusj ? 😬

**Comment by gcmatheusj** [comment]
@lucianopf o erro que coloquei no current behavior

**Comment by gcmatheusj** [comment]
Consegui aqui pessoal, muito obrigado pelo help. 
Por fim, aproveitando a issue e o fato de esta usando a api do pagarme pela primeira vez, gostaria de saber se é possível, quando o status de uma assinatura mudar na api do pagarme, ter alguma forma de por exemplo receber essa info via socket ou algo do tipo, tendo em vista que estou guardando na minha base de dados algumas informações da assinatura de voces pra consultas mais rápidas?

**Comment by lucianopf** [comment]
> Consegui aqui pessoal, muito obrigado pelo help.
> Por fim, aproveitando a issue e o fato de esta usando a api do pagarme pela primeira vez, gostaria de saber se é possível, quando o status de uma assinatura mudar na api do pagarme, ter alguma forma de por exemplo receber essa info via socket ou algo do tipo, tendo em vista que estou guardando na minha base de dados algumas informações da assinatura de voces pra consultas mais rápidas?

Que bom que deu certo @gcmatheusj !! ^^

Temos sim, chamamos de postback, vc pode conferir mais na documentação! 😬 


> O postback em si é uma requisição (POST) que enviamos de volta (BACK) ao seu servidor por meio do parâmetro postback_url, que você indica no momento da criação de transações (transactions) ou de assinaturas (subscriptions). O seu objetivo é notificar a sua aplicação sobre a mudança de status dos objetos mencionados — com isso, você consegue programar tarefas no seu sistema, usando o postback como ponto de partida para outras rotinas.

https://docs.pagar.me/docs/overview-postback-url

**Comment by gcmatheusj** [comment]
Valeu turma!

**Comment by teddiur** [comment]
> Consegui aqui pessoal, muito obrigado pelo help.

O que você fez para resolver? Estou tendo o mesmo problema
