### ISSUE TITLE
submodulo browser no npm não está funcionando

### ISSUE THREAD

**Issue by Thiagokairala** [pagarme/pagarme-js#23]
Boa tarde,

Durante alguns testes que venho realizando hoje, houve um problema no qual eu tentei utilizar o pacote npm em um projeto react, e quando fui importar o módulo deu erro...

o import foi feito de acordo com a documentação, `import pagarme from 'pagarme/browser';`
porém foi apontado que não existia arquivo pagarme.js no pacote pagarme/browser, e realmente não existe, este arquivo apenas existe no modulo pagarme.

**Comment by MarcoWorms** [comment]
Obrigado por reportar o erro!

@derekstavis

**Comment by derekstavis** [comment]
Olá! Desculpe o vacilo, enviamos a build para o NPM faltando um arquivo. Vou publicar a versão 3.0.1 ainda hoje!

**Comment by derekstavis** [comment]
Olá @Thiagokairala! Pode atualizar a versão para 3.0.1 em seu `package.json` que agora vai!!

**Comment by Thiagokairala** [comment]
Muito obrigado =D vou testar hoje a noite e te dou um retorno
