### ISSUE TITLE
Adicionar rota de segmentos

### ISSUE THREAD

**Issue by marisamodolo** [pagarme/pagarme-js#231]
## Description
Precisamos adicionar suporte a rota GET company_segments

### Current Behavior
Hoje não é possivel utilizar a rota company_segments através da pagarmejs

### Expected Behavior
Retornarmos os segmentos ao chamar a função `client.companySegments.all`

**Comment by felipemosci** [comment]
https://github.com/pagarme/paymentlink/issues/58
