### ISSUE TITLE
Integracao da API em um Backend Adonis JS.

### ISSUE THREAD

**Issue by LucasKeiti28** [pagarme/pagarme-js#244]
## Description
Integracao da API em um Backend Adonis JS.

## My Setup
- Adonis Versio:    "4.1.0",
- Project Version: Pagarme API 2019

- [ ] Realizar um pagamento teste

### Current Behavior
```
{ ApiError: Pagar.me API error. Check error's "response" property for more details.
    at new ApiError (/Users/lucaskeiti/pagarme/node_modules/pagarme/pagarme.js:9236:107)
    at /Users/lucaskeiti/pagarme/node_modules/pagarme/pagarme.js:8484:39
    at process._tickCallback (internal/process/next_tick.js:68:7)
  name: 'ApiError',
  response:
   { errors: [ [Object] ],
     url: '/transactions',
     method: 'post',
     status: 400 } }
```

### Codigo
```
async store({ request, response }) {
    try {
      const data = request.all();

      const payment = await Payment.create(data);

      pagarme.client.connect({ api_key: Env.get("PG_API") }).then(client =>
        client.transactions.create({
          amount: 1000,
          card_number: "4111111111111111",
          card_holder_name: "abc",
          card_expiration_date: "1225",
          card_cvv: "123"
        })
      );

      return response.status(200).send(payment);
    } catch (error) {
      return response.status(400).send(error);
    }
  }

```

**Comment by lucianopf** [comment]
Bom dia, tudo certo? :grimacing: 

Aparentemente vc está tentando criar uma transação faltando alguns campos :grimacing: 

Vc pode conferir a referência dos campos necessários aqui em https://docs.pagar.me/reference#criar-transacao

Um dica é nesse objeto de erro retornado vc exibir o que está contido em  `response.errors` pois lá indicamos os campos errados e qual o valor esperado :grimacing:

**Comment by LucasKeiti28** [comment]
Legal, deu certo! Nao tinha encontrado esse link com os campos.

obrigado!
