### ISSUE TITLE
CardHash não funciona em React Native

### ISSUE THREAD

**Issue by gumiranda** [pagarme/pagarme-js#254]
## Problema
Olá,

Gostaria de saber como funciona essa lib numa aplicação React Native, pois sempre que testo ele dá o erro:
Unable to resolve module url from ...

Depois disso, eu acabei instalando a lib url e o erro foi corrigido, porém agora o erro está:
Unable to resolve module http from...

Já tentei usar rn-nodeify, já tentei usar node-libs-react-native , já tentei copiar esse cara https://github.com/sugaith/Cloud-Credit-App-with-Pagar.me ,já tentei usar webview ,tentei usar 👍 
global.self = { fetch };
const pagarme = require('pagarme/browser');

pagarme.client.connect({ api_key: 'SUA_API_KEY' })
  .then(client => client.cards.create({
    card_number: '4018720572598048',
    card_holder_name: 'Aardvark Silva',
    card_expiration_date: '1122',
    card_cvv: '123',
  }))
  .then(card => console.log(card.id));

e deu Error: Error during encryption. Original error: Error: secure random number generation not supported by this browser
use chrome, FireFox or Internet Explorer 11.

Não queria passar os dados do cartão de crédito em texto claro pela rede
 Tentei até encryptar o cartão manualmente como vcs ensinam na documentação, pegando id e chave pública e encryptei usando react-native-rsa depois gerei o base 64 concatenei com o id e enviei pra vcs, retornou conteúdo encryptado inválido.

**Comment by bmamone** [comment]
Mesmo ocorrendo aqui.

Utilizando [`react-native-rsa-native`](https://github.com/amitaymolko/react-native-rsa-native). Provavelmente algum problema com o schema PKCS1.

Não encontrei solução fácil, acredito ser necessário um port das libs nativas para RN, ou obfuscar os dados de cartão de outra forma e lidar com o hashing no server-side.

PS: cuidado com a utilização de `api_key` no frontend!

**Comment by bmamone** [comment]
Consegui fazer o `card_hash` utilizando uma WebView vide sugestão na issue https://github.com/pagarme/pagarme-js/issues/107#issuecomment-549470143

**Comment by fabianosilvait** [comment]
Também estou com o mesmo problema aqui.

pagarme.client.connect({ encryption_key: 'ak_test_XXXXXXXXXXXXXXXXXXXXXXXXXXX' })
    .then((client) => {
      return client.security.encrypt({
        card_number: '4111111111111111',
        card_holder_name: 'abc',
        card_expiration_date: '1225',
        card_cvv: '123',
      })
    })
    .then((card_hash) => console.log(card_hash))

Error: Error during encryption. Original error: Error: secure random number generation not supported by this browser
use chrome, FireFox or Internet Explorer 11

**Comment by franzon** [comment]
Consegui utilizar a biblioteca importando a partir do `pagarme/browser`, por exemplo:

`
import pagarme from 'pagarme/browser';
`

É importante verificar se está usando a Chave de criptografia e **não** a Chave de API, dessa forma:

```
const client = await pagarme.client.connect({
  encryption_key: 'ek_test_...',
});
```

**Comment by fabianosilvait** [comment]
Continuo com o mesmo problema @franzon, você conseguiu gerar o hash no react native? aqui não vai de jeito nenhum... kkkkk

WARN     Possible Unhandled Promise Rejection (id: 2):
Error: Error during encryption. Original error: Error: secure random number generation not supported by this browser
use chrome, FireFox or Internet Explorer 11


`import React from 'react';`
`import { StyleSheet, View, Text, Button, } from 'react-native';`
`import pagarme from 'pagarme/browser';`
` `
`export default function App() {`
` `

  `async function processaCard(){`
        
    `pagarme.client.connect({ encryption_key: 'ek_test_****************************' })`
  `  .then((client) => {`
`      return client.security.encrypt({`
`        card_number: '4111111111111111',`
`        card_holder_name: 'abc',`
`        card_expiration_date: '1225',`
`        card_cvv: '123',`
 `     })`
 `   })`
`    .then((card_hash) => console.log(card_hash))`
`  }`

 ` return (`
   ` <View style={styles.container}>`
    `  <Text style={styles.label}>Cartão de Crédito</Text>`
    ` <Button title='Processar' onPress={processaCard}></Button>`
   ` </View> `
 `    `
`);`
`};`

**Comment by franzon** [comment]
Aqui deu certo sim, @fabianosilvait.

Qual versão do React Native e da pagarme você está utilizando?

**Comment by fabianosilvait** [comment]
@franzon, quais versões você esta usando?

"pagarme": "^4.11.0",
"react": "16.11.0",
"react-native": "0.62.2"

**Comment by franzon** [comment]
Vish, inicializei um projeto novo e realmente está acontecendo o erro. Mas no meu projeto com umas versões um pouco mais antigas está funcionando.

Estou usando essas versões:

"pagarme": "^4.11.0",
"react": "16.8.6",
"react-native": "0.60.3"

**Comment by fabianosilvait** [comment]
@franzon, criei um novo projeto com as versões que você me passou, usei o mesmo código do comentário acima e não deu também. o que será que pode ser?

"dependencies": {
    "pagarme": "^4.11.0",
    "react": "16.8.6",
    "react-native": "0.60.3"
  },

![Screenshot_20200619-120532](https://user-images.githubusercontent.com/61808503/85147601-7bdf7e80-b225-11ea-8f25-be1bb62da266.png)

**Comment by franzon** [comment]
@fabianosilvait que coisa estranha, criei um projeto novamente e agora deu certo...

Aqui está o código completo:

```
import React from 'react';
import {Button, SafeAreaView} from 'react-native';
import pagarme from 'pagarme/browser';

const App = () => {
  async function generateHash() {
    const client = await pagarme.client.connect({
      encryption_key: 'ek_test_....',
    });

    const hash = await client.security.encrypt({
      card_number: '1234123412341234',
      card_holder_name: 'John Doe',
      card_expiration_date: '1221',
      card_cvv: '321',
    });

    alert(hash);
  }

  return (
    <SafeAreaView>
      <Button title="Gerar hash" onPress={generateHash} />
    </SafeAreaView>
  );
};

export default App;
```
![photo5145711119913035924](https://user-images.githubusercontent.com/11821142/85169261-ef8f8480-b241-11ea-926c-7c1da1c2dedc.jpg)

**Comment by franzon** [comment]
@fabianosilvait acho que descobri o que era, aqui estava funcionando porque eu estava com o Debug ativado. Quando desativei parou de funcionar...

**Comment by fabianosilvait** [comment]
@franzon eu só testei no modo debug e não funciona... :/

**Comment by franzon** [comment]
Criei uma biblioteca pra gerar o card_hash pelo React Native, seguindo esses passos [aqui](https://docs.pagar.me/reference#gerando-card_hash-manualmente).

Caso alguem precise: [react-native-pagarme-card-hash](https://github.com/franzon/react-native-pagarme-card-hash)

**Comment by gumiranda** [comment]
> Criei uma biblioteca pra gerar o card_hash pelo React Native, seguindo esses passos [aqui](https://docs.pagar.me/reference#gerando-card_hash-manualmente).
> 
> Caso alguem precise: [react-native-pagarme-card-hash](https://github.com/franzon/react-native-pagarme-card-hash)

Boaa, apliquei aqui e funcionou!

**Comment by gumiranda** [comment]
Consegui
