### ISSUE TITLE
Duvida com Postback

### ISSUE THREAD

**Issue by jpinhani** [pagarme/pagarme-js#264]
Olá,

Estou com duvidas referente ao processo de PostBack do Pagarme.
Consigo receber as mensagens normalmente em minha URL de backend, no entanto as mensagens não param de vir, é como se o Pagarme não entende-se que eu ja tenha recebido a mensagem.

Com base nisso, verifiquei que devo devolver o Status Code 200, para que o Delivery pare.
Como seria isso?

Estou usando Node.js e utilizei como exemplo a issue Postback #170 (https://github.com/pagarme/pagarme-js/issues/170) .

```js
const pagarme = require('pagarme')
const qs = require('qs')

const validatePostback = (req, res, next) => {
  const apiKey = 'SUA_API_KEY'
  const verifyBody = qs.stringify(req.body)
  const signature = req.headers['x-hub-signature'].replace('sha1=', '')

  if (!pagarme
    .postback
    .verifySignature(apiKey, verifyBody, signature)
  ) {
    return res.json({error: 'Invalid Postback'})
  }

  return res.json({message: 'postback válido'})
}
```

devo retornar algo como return res.status(200) ?

**Comment by diomalta** [comment]
Exato, deve ficar assim: 

`res.status(200).json({ message: 'postback válido' })`

A pagarme só para de mandar quando ela recebe a informação que o postback foi recebido com sucessp pelo destino.

**Comment by jpinhani** [comment]
Show testei aqui e deu certo, muito obrigado.
