### ISSUE TITLE
PostBack não retornando

### ISSUE THREAD

**Issue by Guilherme300** [pagarme/pagarme-js#266]
Estou tentando fazer com que eu receba a notificação do pagarme após eu criar a subscrição de um plano e quando houver mudança na transação, porém nada é enviado. Tentei pelo pipedream e pelo requestbin e não recebem nada. Tabém já ativei a notificação no dashboard.

**Comment by Guilherme300** [comment]
Já fiz uma requisição para ver se foi enviado algo pelo postback, todavia ele me retorna somente [], nenhum error ou sucess.

**Comment by Guilherme300** [comment]
Estou utilizando a SDK do javascript

**Comment by lucianopf** [comment]
Bom dia @Guilherme300 pode nos passar como a request ta indo pfv? 🙏 

Vs saberia também nos dizer o id da company que vc está testando?

**Comment by murilohns** [comment]
@Guilherme300, o produto de assinaturas não envia _postback_ de **atualização** de transações, apenas de **criação**.

Mas sempre que o status da assinatura for atualizado, você receberá um _postback_ com da assinatura com essa atualização

**Comment by Guilherme300** [comment]
Luciano, eu fiz a request método javascript e curl, ambos não deram nenhum retorno, segue o código:
`#!/bin/bash

curl -X POST 'https://api.pagar.me/1/subscriptions' -H 'content-type: application/json' -d '{
    "api_key": "aqui vai minha api de teste", 
    "payment_method": "credit_card", 
    "plan_id": "490677", 
    "card_hash": "2859030_xlq958G9BzED2NAGasfVI4vSdQMw619dfkPpi5pIKcPIM7e3/TIWjVS1snu9hifHkI/USvHopSLuYCxmepk+iDB0JJ+aknWWHBemUE4YIBFMVsijqDpFMJbEJtxUGLzrLIEserScsH2bcM+uvUnT98iiRhUqDw7sfe7eFPaX7Pf5P9ZECStUaZ/JB1R2paw+ijHnHGmh9vCGvyhSCGvFvHVmZs5q489EZTCw7sz5+kCEvmuL0+sXgu0MhZYlx4Zut5TTRJyhJSpWglPL88dbchs/2LY9oEBWgnI8y7l9+H/zU/ws0NYh2i99DA3+tylNoHIFUuGG0adss2fdEHoqfQ==", 
    "customer": {
        "address": {
            "neighborhood": "Cidade Monções", 
            "street": "Rua Dr.Geraldo Campos Moreira", 
            "street_number": "240", 
            "zipcode": "04571020"
        }, 
        "document_number": "92545278157", 
        "email": "jappleseed@apple.com", 
        "name": "John Appleseed", 
        "phone": {
            "ddd": "11", 
            "number": "15510101"
        }
    }, 
    "postback_url": "https://9ddeb46f375db886dcddb1e5d7f06b9f.m.pipedream.net"
}'
`

**Comment by Guilherme300** [comment]
Murilo, a assinatura está sendo feita, porém o postback não está sendo enviado de nenhuma forma, nem na criação nem na atualização da transação.

**Comment by Guilherme300** [comment]
Luciano, só não entendi oque seria o id da company, pode me iluminar sobre isso para eu enviar aqui ?

**Comment by Rafael-Peres** [comment]
@Guilherme300 conseguiu resolver?

**Comment by Guilherme300** [comment]
Consegui sim. Me desculpem por não ter fechado essa issue antes. 

Segue a resposta que resolveu minhas dúvidas para quem tiver posteriormente.

![image](https://user-images.githubusercontent.com/46011575/93577487-815a7b00-f972-11ea-899a-00cb5b37e502.png)
