### ISSUE TITLE
Upload 3.0.1 (and new versions) to CDN and link it inside the documentation

### ISSUE THREAD

**Issue by MarcoWorms** [pagarme/pagarme-js#27]
We need to add this to the deploy process, also we always need to update the docs with the newest CDN. Is it possible to make a "latest" CDN link @derekstavis?

**Comment by derekstavis** [comment]
I have pushed version 3.0.1 to Pagar.me's CDN at the time of 3.0.1 release. Since minor versions are automatically updated when uploading to CDN, we don't need to update the README link this release.
