### ISSUE TITLE
Pergunta sobre encryption_key

### ISSUE THREAD

**Issue by filipesarturi** [pagarme/pagarme-js#273]
É seguro informar a encryption_key no front-end? Pois li que para criar um card hash é necessário informar, como mostra o código da documentação abaixo:

`const pagarme = require('pagarme')

pagarme.client.connect({ encryption_key: 'SUA_ENCRYPTION_KEY' })
  .then(client => {
    return client.security.encrypt({
      card_number: '4111111111111111',
      card_holder_name: 'abc',
      card_expiration_date: '1225',
      card_cvv: '123',
    })
  })
  .then(card_hash => console.log(card_hash))`

**Comment by mrlmaia** [comment]
Sim, você nao deve informar a sua api key no front

**Comment by filipesarturi** [comment]
Sim, porém há duas chaves: api_key e encryption_key. Acredito que o propósito da encryption_key seria de gerar o card hash mesmo, portanto creio que não teria problema de usar ela no front

**Comment by murilohns** [comment]
@filipesarturi, a encryption key pode ficar no front-end sim! O card_hash é gerado com a `encryption_key`, e só pode ser utilizado por sua `api_key` posteriormente.

Se alguém tentar usar seu card_hash com outra `api_key` ocorrerá um erro
