### ISSUE TITLE
acquirer_response_code

### ISSUE THREAD

**Issue by filipesarturi** [pagarme/pagarme-js#274]
Alguém possui os códigos de retorno de erro da adquirente (acquirer_response_code)? Não encontrei em lugar algum :/

**Comment by Matheus-Maciel** [comment]
Bom dia @filipesarturi 
No zendesk da Pagar.me há um documento contendo os códigos de retorno, segue o link: https://pagarme.zendesk.com/hc/pt-br/articles/205461615-Motivos-de-recusa-de-uma-transação
