### ISSUE TITLE
Criar cartão com card_hash

### ISSUE THREAD

**Issue by Yuu-Kuuhaku** [pagarme/pagarme-js#276]
Desenvolvi um front em angular. no começo estava fazendo o card_hash sem lib usando o código dessa lib. Instalei essa lib e crio o card_hash sem problemas. mas quando envio para o back e tentam cadastrar o cartão retorna um erro 500 

error:
debug: Array(1)
0: {message: "Pagar.me server error"}
length: 1
__proto__: Array(0)
message: "Pagar.me API error. Check error's "response" property for more details."
status: "error"

**Comment by murilohns** [comment]
@Yuu-Kuuhaku, consegue postar um exemplo do trecho de código, por favor?

**Comment by Yuu-Kuuhaku** [comment]
descobri que estava usando a api_key para criptografar o card_hash ao inves da encryption_key.
