### ISSUE TITLE
Pagamento está recusando sempre em ambiente de testes

### ISSUE THREAD

**Issue by mrlmaia** [pagarme/pagarme-js#285]
## Description
Tenho uma integracao feita com a Pagarme e, em ambiente de testes, a transaction sempre retorna um status = 'refused' e um status_reason = 'acquirer', sendo que estou enviando como cpf do customer 12345678909 e um cvv que nao começa com 6

**Comment by willian-soaresferreira** [comment]
Oi @mrlmaia, tudo bem? Meu nome é Willian e faço parte do time de Suporte Técnico da Pagar.me.

Me parece ser algo relacionado à requisição enviada e/ou relacionado ao seu cadastro, nesse caso pode por favor enviar um e-mail para suporte@pagar.me informando seu e-mail de cadastro? Assim te ajudamos por lá :)

**Comment by mrlmaia** [comment]
Vou enviar, obrigado!
