### ISSUE TITLE
Ionic 2

### ISSUE THREAD

**Issue by vladiusdf** [pagarme/pagarme-js#30]
*Estou usando chaves de teste no momento.

Quando tento fazer a geração do hash utilizando a api_key ou a secret. Ele informa que eu devo utilizar uma chave ou secret válida. Em ambos os carros eu recebo a mensagem de erro.

**Comment by MarcoWorms** [comment]
Olá, por acaso vc atualizou para a versão 3.0.1 do pacote? A gente corrigiu esse bug nela :). Se vc ja tiver atualizado, tem como mandar prints do erro e da implementação que vc fez para podermos dar uma olhada?

**Comment by vladiusdf** [comment]
Atualizei sim,

Não sei se um print será de grande vália, mas posso explicar os passos que realizei.

Objetivo: Preciso conectar utilizando a api ou o secret e gerar o hash do cartão para submeter a um serviço.

Obs: Ainda tenho o código da api (pagarme) antigo para fins de teste e nela as chaves funcionam e geram o hash.

Como funciona: Antes da versão 3.0.1 conseguia fazer o teste quando enviava da primeira view do ionic e estava debugando no celular usando o comando "Ionic run android --lc", e quando eu colocava na view correta e no celular ele gerava um erro dizendo que eu deveria informar uma "valid Key"

Na versão: 3.0.1 ele reclama que o secret ou o api não são válidos.

Obs: O conect funciona perfeitamente em todos os cenários, tanto que via inspect de serviços consigo ver o retorno do profile. Porém ele gera erro de chave inválida.

**Comment by MarcoWorms** [comment]
É dificil conseguir te responder assertivamente ou identificar o problema sem ver o código :/

**Comment by luccasmaso** [comment]
@MarcoWorms Peguei aqui pra testar a versão 3.0.1 e talvez o erro dele tenha a ver com o meu. 

To tendo problema com `Access-Control-Allow-Origin` nesse request que a lib faz abaixo. Não sei se do lado do servidor esse endpoint em específico está limitando o origin para o domínio e subdomínio de produção cadastrado no dashboard e bloqueiam pro localhost.

![image](https://cloud.githubusercontent.com/assets/1427231/24665909/18ccbbdc-1935-11e7-859a-e626df4c9670.png)

**Comment by MarcoWorms** [comment]
@luccasmaso valeu pelo print cara, vou debugar aqui com o @derekstavis pra chegar na raíz disso e dar uma resposta pra vcs.

**Comment by MarcoWorms** [comment]
Então, rodando um teste rápido aqui o card_hash foi gerado normalmente.

```js
var pagarme = require("pagarme")

pagarme.client.connect({
  encryption_key: 'MINHA_ENCRYPTION_KEY'
})
  .then(client => client.security.encrypt({
    card_number: '4111111111111111',
    card_holder_name: 'abc',
    card_expiration_date: '1225',
    card_cvv: '123',
 }))
    .then(console.log)
```

Por acaso vcs estão levantando um servidor local para testar? Se abrir o html diretamente não funciona por causa do `cors`

**Comment by luccasmaso** [comment]
Ta, entendi o que ta acontecendo @MarcoWorms. Eu to fazendo require em `pagarme/browser`, fazendo `require("pagarme")` funcionou. Devo fazer require do pagarme todo mesmo querendo usar apenas essa função de hash no cartão?

**Comment by MarcoWorms** [comment]
Interessante, não sei te responder isso, vou ver aqui com o @derekstavis que é nosso webpack-man e ja te voltamos com uma resposta (e talvez um fix)

**Comment by vladiusdf** [comment]
`import { Component } from '@angular/core';
import { NavController, NavParams, ViewController, AlertController } from 'ionic-angular';

import { Service } from '../../providers/service';

import pagarme from 'pagarme'


@Component({
  selector: 'page-payment',
  templateUrl: 'payment.html'
})
export class PaymentPage {

  valor : number;
  card : any = {
    cardHolderName : '',
    cardCVV: ''

  };
  agendamento : any = {};
  cardExpiration : string = '';
  cardNumber : string = '';
  public cardMask = [ /[0-9]/, /\d/, /\d/, /\d/, ' ', /\d/, /\d/, /\d/, /\d/, ' ', /\d/, /\d/, /\d/, /\d/, ' ', /\d/, /\d/, /\d/, /\d/];
  public cardValid = [ /[0-1]/, /[0-9]/,'/', /[0-9]/, /[0-9]/];

  constructor(
    public navCtrl: NavController,
    private viewCtrl: ViewController,
    private service : Service,
    private alertCtrl : AlertController,
    public navParams: NavParams
  ) {
    this.agendamento = this.navParams.get('agendamento');
  }

  ionViewDidLoad() {
    console.log('ionViewDidLoad PaymentPage');
  }
  dismiss()
  {
    this.viewCtrl.dismiss();
  }
  doPayment() {
    

    let card = {
      card_number: this.card.cardNumber,
      card_holder_name: this.card.cardHolderName,
      card_expiration_date: _expiration,
      card_cvv: this.card.cardCVV
    }

//api_key : 'ak_test_u1.....',
  pagarme.client.connect({ encryption_key : 'ek_test_baRA....'})
  .then(
    client => {
      client.security.encrypt(card).then(card_hash => {

        let _d = {
          "Id": window['usuario'].Id,
          "Voucher": this.agendamento.Voucher,
          "Hash": card_hash,
          "Valor": this.agendamento.Valor,
          "Cupom": ""
        }
        this.service.doPaymentCartao(_d).subscribe(
          data => {
            this.alertCtrl.create(
              {
                title: 'Pagamento',
                subTitle: data.Data,
                buttons: ['OK']
              }
            ).present();
          },
          err => {
            this.alertCtrl.create(
              {
                title: 'Erro ao realizar pagamento!',
                subTitle: err,
                buttons: ['OK']
              }
            ).present();
          }
        )

      },error => {

        this.alertCtrl.create(
          {
            title: 'Erro ao gerar o hash!',
            subTitle: error,
            buttons: ['OK']
          }
        ).present();
      });
    },
    error => {

      this.alertCtrl.create(
        {
          title: 'Error ao autenticar',
          subTitle: error,
          buttons: ['OK']
        }
      ).present();
    }
  );

  }
}
![pagamento_erro](https://cloud.githubusercontent.com/assets/8129196/24670438/63df06ca-1944-11e7-9e46-c19d792e1b35.jpg)
`

**Comment by derekstavis** [comment]
Opa @luccasmaso , quando usando o Webpack, recomendo vc importar diretamente o `pagarme` e não o `pagarme/browser`. O `pagarme/browser` é um pré-compilado usando Webpack. Conseguimos reproduzir seu erro, e vamos averiguar o comportamento. Voltamos a comentar aqui quando encontrarmos o motivo!

Obrigado pelos reports!! :+1:

**Comment by vladiusdf** [comment]
Eu que agradeço a presteza do atendimento. Parabéns pela Api apesar dos erros ela está muito boa e fácil de usar. Aguardando feedbacks.

**Comment by MarcoWorms** [comment]
@luccasmaso resolvi esse problema nesse PR aqui https://github.com/pagarme/pagarme-js/pull/33 :)

**Comment by MarcoWorms** [comment]
A versão 3.0.2 ja está em produção e resolve esse problema do browser. Caso tenham novos problemas é só abrir outra issue :)
