### ISSUE TITLE
Erro ao se conectar na api. Messagem de erro: "You must supply a valid API key"

### ISSUE THREAD

**Issue by igorsilva3** [pagarme/pagarme-js#334]
Criei uma função básica para se conectar ao serviço.
```ts 
  import { client } from 'pagarme'
  
  export async function connect(apiKey: string | undefined) {
    try {
      console.log(apiKey) // Minha chave api 
      return await client.connect({ api_key: apiKey })
    } catch (error) {
      throw error
    }
  }
```

Criei também um teste unitário:
```ts
import { connect } from '../../src/services/pagarme'
import { env } from '../../src/env'

describe('To connect pagarme', () => {
  it('should to be able return success', async () => {
    const apiKey = env('PAGARME_API_KEY')

    const connected = await connect(apiKey)

    expect(connected).toHaveProperty('acquirers')
  })
})
```
Formato da chave api gerada na v5: sk_qrezZl4TrZFRb1Vx
Formato da chave api gerada na v4: ak_test_grXijQ4GicOa2BLGZrDRTR5qNQxJW0

Quando utilizo a chave api gerada na versão 4 consigo me conectar com sucesso ao serviço e o teste passa, porém utlizando a chave api gerada pela versão 5, é me retornado esse erro: "You must supply a valid API key"

Sinceramente não sei o que estou fazendo de errado

**Comment by pcsantana** [comment]
Olá Igor!

Conseguiu resolver?
Estou com o mesmo problema. Acredito que a lib pagarme-js ainda não dê suporte para a v5 :/

**Comment by igorsilva3** [comment]
Olá, Paulo.

Infelizmente não consegui resolver. Também pensei essa mesma possibilidade.

**Comment by igorsilva3** [comment]
Olá, @pcsantana tudo bem?

Cara tive um pequeno avanço kkkk

Lendo a documentação da nova versão da API, percebi que eles alteraram a forma de autenticação.

Basicamente você vai ter que passar um objeto contendo duas propriedades: username e password, tendo isso em mente é só passar no username a chave api e deixa no password uma string vazia.

Teoricamente era para funcionar, fiz o teste na referência da api (onde podemos testar sem precisar baixar a biblioteca). Nessa parte funcionou de boa.

Tentei implementar da mesma maneira no código dessa seguinte maneira:
```ts
export async function connect(apiKey: string | undefined) {
  return await client.connect({ 
    email: apiKey,
    password: ''
  })
}
```
E infelizmente é me retornado outro erro kkkkk

![image](https://user-images.githubusercontent.com/48392942/142937355-dab3ce49-01ee-499e-a9f2-ea42ef938118.png)

**Comment by flpms** [comment]
Também estou com o mesmo problema e sem saber se tem como alterar as versões

**Comment by magnomoreira** [comment]
Bom dia galera, tudo bem?
Então, nossa SDK pagarme-js integra com a versão 4, para integrar com a versão 5 lançamos uma nova SDK.
Criamos essa nova SDK com a junção da Pagarme com a Mundi, que é a pagarme-core-api-js. Caso vocês queiram utilizar essa versão, terão que instalar o pacote referente a nova sdk que é o @pagarme/sdk.

**Comment by magnomoreira** [comment]
Fala @pcsantana corrigindo. O endereço é esse aqui https://github.com/pagarme/pagarme-core-api-nodejs
