### ISSUE TITLE
Session does not have any test

### ISSUE THREAD

**Issue by LeoNero** [pagarme/pagarme-js#34]
I believe that the resource https://github.com/pagarme/pagarme-js/blob/master/lib/resources/session.js should have a test (there is no session.spec.js) :)

**Comment by MarcoWorms** [comment]
@LeoNero could you pick this one for the next sprint? ;)

**Comment by LeoNero** [comment]
Yeaaaah :D @MarcoWorms

**Comment by MarcoWorms** [comment]
Todo:
[ ] - Add test for session
[ ] - Ensure session id is valid (just like API key testing)
