### ISSUE TITLE
(bug) only card number validation

### ISSUE THREAD

**Issue by gabrielrtakeda** [pagarme/pagarme-js#41]
# Description
When I tried to validate only the `card_number`,  the following error was dispatched:

```
Uncaught TypeError: Cannot read property 'replace' of undefined
```

I use the code below:
```js
import pagarme from 'pagarme'

pagarme.validate({ card: { card_number: '5545497548400992' } })
```

If I pass the `card_expiration_date` even if it is an empty string, the error has gone.

## Package version
```
pagarme@^3.0.2:
  version "3.0.2"
  resolved "https://registry.yarnpkg.com/pagarme/-/pagarme-3.0.2.tgz#4ff05cd9234abbadb95d71cfa6c935650e9a8a90"
```

**Comment by MarcoWorms** [comment]
Thanks for the report! I will make sure we will handle these validators errors better, this card validation should warn you when you don't send all the card info :)

**Comment by MarcoWorms** [comment]
https://github.com/pagarme/pagarme-js/pull/45

**Comment by MarcoWorms** [comment]
The PR was merged. If you have any more problems with this feel free to open another issue :D

**Comment by yconselvan** [comment]
How can i get this update? Documentation at https://docs.pagar.me/docs/obtendo-os-dados-do-cartao  shows script tag <script src="https://assets.pagar.me/pagarme-js/3.0/pagarme.min.js"></script> that contains the same problem.
