### ISSUE TITLE
(bug) invalid card number validation

### ISSUE THREAD

**Issue by gabrielrtakeda** [pagarme/pagarme-js#42]
# Description
When I tried to validate an invalid `card_number`,  the following error was dispatched:

```
Uncaught TypeError: Cannot read property '0' of undefined
```

I used the **1231231231231231** dummy card_number like
```js
import pagarme from 'pagarme'

pagarme.validate({ 
  card: { 
    card_number: '1231231231231231',
    card_expiration_date: ''
  } 
})
```

## Package version
```
pagarme@^3.0.2:
  version "3.0.2"
  resolved "https://registry.yarnpkg.com/pagarme/-/pagarme-3.0.2.tgz#4ff05cd9234abbadb95d71cfa6c935650e9a8a90"
```

**Comment by MarcoWorms** [comment]
Thanks for the issues :D, just like in #41 I will make sure we give a better experience when unexpected input is sent.

**Comment by MarcoWorms** [comment]
https://github.com/pagarme/pagarme-js/pull/45

**Comment by MarcoWorms** [comment]
The PR was merged. If you have any more problems with this feel free to open another issue :D
