### ISSUE TITLE
add .all() shortcut on JSDocs

### ISSUE THREAD

**Issue by MarcoWorms** [pagarme/pagarme-js#47]
currently .all() shortcut for .find({}) is not well documented on JSDocs. This is true for almost all endpoints. We need to add JSDocs meta-comments on those endpoints to document this better.

**Comment by guarilha** [comment]
Modules that don't have the `all()` documentation: 

- https://pagarme.github.io/pagarme-js/module-recipients.html
- https://pagarme.github.io/pagarme-js/module-session.html
- https://pagarme.github.io/pagarme-js/module-splitRules.html
- https://pagarme.github.io/pagarme-js/module-postbacks.html
- https://pagarme.github.io/pagarme-js/module-events.html
- https://pagarme.github.io/pagarme-js/module-invites.html
- https://pagarme.github.io/pagarme-js/module-transactions.html
- https://pagarme.github.io/pagarme-js/module-gatewayOperations.html

**Comment by MarcoWorms** [comment]
thanks :D

**Comment by MarcoWorms** [comment]
https://github.com/pagarme/pagarme-js/pull/57
