### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by guarilha** [pagarme/pagarme-js#50]
https://pagarme.github.io/pagarme-js/module-transactions.html

The `update` API reference link is pointing to the wrong anchor.

**Comment by MarcoWorms** [comment]
note: We don't have this link in the new docs yet.

**Comment by MarcoWorms** [comment]
lets centralize this discussion on https://github.com/pagarme/pagarme-js/issues/49 because it relates to the same issue :)

**Comment by MarcoWorms** [comment]
https://github.com/pagarme/pagarme-js/pull/58

**Comment by guarilha** [comment]
I'll close this issue and we track this with #49
