### ISSUE TITLE
Refund is ignoring the amount property

### ISSUE THREAD

**Issue by guarilha** [pagarme/pagarme-js#51]
Without it, we can't implement partial refunds. 
```
const refund = (opts, body) =>
  request.post(opts, routes.transactions.refund(body.id), {})
```
https://github.com/pagarme/pagarme-js/blob/master/lib/resources/transactions.js#L98

**Comment by MarcoWorms** [comment]
https://github.com/pagarme/pagarme-js/pull/53

**Comment by MarcoWorms** [comment]
reopening to close when we merge the PR :)
