### ISSUE TITLE
Capture is ignoring the amount property

### ISSUE THREAD

**Issue by guarilha** [pagarme/pagarme-js#52]
Without it, we can't implement partial captures. 
```
const capture = (opts, body) =>
  request.post(opts, routes.transactions.capture(body.id), {})
```
https://github.com/pagarme/pagarme-js/blob/master/lib/resources/transactions.js#L79

**Comment by MarcoWorms** [comment]
https://github.com/pagarme/pagarme-js/pull/53

**Comment by MarcoWorms** [comment]
reopening to close when we merge the PR :)
