### ISSUE TITLE
Pagamento com cartão de crédito no ambiente de testes respondendo 'api_key está faltando'

### ISSUE THREAD

**Issue by fabiolnm** [pagarme/pagarme-js#72]
Ao tentar gerar o card_hash usando o form de checkout, estou tomando este erro:

```
{
  "errors": [
    {
      "type":"invalid_parameter",
      "parameter_name":"api_key",
      "message":"api_key está faltando"}
  ],
  "url":"/transactions/card_hash_key?encryption_key=<ENC_KEY>","method":"get"
}
```

Pode estar relacionado com https://github.com/pagarme/pagarme-js/issues/17.

Já tinha conseguido criar transações mais cedo - parou de funcionar há pouco.

**Comment by derekstavis** [comment]
Estivemos fazendo alguns deploys no ambiente de testes e provavelmente eles afetaram a resposta do card_hash. Confirmo que também não está funcional para mim. A equipe responsável foi informada e está trabalhando para reverter o quadro.

Muito obrigado pelo seu report :smile:

**Comment by wilkmaia** [comment]
@fabiolnm pode testar agora?

Acreditamos estar tudo bem :)

**Comment by fabiolnm** [comment]
O `card_hash` está sendo gerado mas as transações de teste não estão sendo autorizadas: 
```
"#<PagarMe::ValidationError: Nome do portador do cartão está faltando, Data de expiração do cartão está faltando, Token do número do cartão está faltando>
```

**Comment by fabiolnm** [comment]
```
   PagarMe::Subscription.create(
      card_hash:          @card_hash,
      ...
   )
```

**Comment by wilkmaia** [comment]
Identificamos o problema, @fabiolnm.

Obrigado por relatar :)

Ele será corrigido logo logo.

**Comment by derekstavis** [comment]
Olá @fabiolnm, seu problema deve estar resolvido agora! Sinta-se confortável para reabrir a issue caso você esteja experienciando o mesmo problema!

**Comment by lucazin** [comment]
Mesmo Problema pra mim so que em .net  gerei o cardhash com os dados do meu cartao pessoal e nada.

**Comment by phmb2** [comment]
Ao tentar fazer uma transação com cartão de crédito está retornando o erro Nome do portador do cartão está faltando. É gerado card_hash, porém não é realizado uma transação.
