### ISSUE TITLE
Que amadorismo e esse de atualizar a card_hash e validações sem avisar previamente?

### ISSUE THREAD

**Issue by fabiozaffani** [pagarme/pagarme-js#73]
Alguém explica? Ter dois sites em produção parando de funcionar da noite para o dia porque vocês atualizaram os códigos, sem nenhum aviso prévio, é bem complicado.

Melhor ainda que a única  mensagem de erro que retorna do sistema é:
"Error: card_hash inválido. Para mais informações, consulte nossa documentação em https://pagar.me/docs."

**Comment by murilohns** [comment]
@fabiozaffani Pedimos desculpas pelo transtorno causado.

Atualmente estamos trabalhando para melhorar os processos de segurança de nosso sistema, e infelizmente essa atualização acabou afetando algumas integrações.

Quero ressaltar que o problema não foi causado por uma mudança de comportamento na geração de _card_hashes_ mas sim por uma quebra na integração com nossa API, ocasionado por um problema não mapeado previamente. 

Como seu problema já foi resolvido, estamos fechando essa Issue, mas você pode reabri-lá quando quiser.

Também gostaria de dizer que estamos sempre abertos a sugestões para melhorar os nossos processos, então sinta-se a vontade para opinar ou sugerir algo.

Att.
