### ISSUE TITLE
Wrong example of how get a client connection on docs

### ISSUE THREAD

**Issue by flyingluscas** [pagarme/pagarme-js#75]
I've noticed a wrong example of how to get a client connection at https://pagarme.github.io/pagarme-js/module-client.html#~connect, is using lower camel case to pass the keys, it's a silly error that could be solved with de example below:

``` js
// API Key Authentication
pagarme.client.connect({ api_key: 'ak_test_y7jk294ynbzf93' })

// Encryption Key Authentication
pagarme.client.connect({ encryption_key: 'ek_test_y7jk294ynbzf93' })
```

**Comment by MarcoWorms** [comment]
Awesome! Could you open a PR fixing this please? :D

**Comment by flyingluscas** [comment]
Yes sir!
