### ISSUE TITLE
Callback de erro no checkout transparente

### ISSUE THREAD

**Issue by raphaelmonteiro** [pagarme/pagarme-js#80]
Não estou conseguindo fazer a captura de falha de pagamento utilizando o checkout transparente. 

Entendo que não existe uma transactionId mas gostaria de capturar uma falha no pagamento ou alguma coisa do tipo para eu registrar que houve uma tentativa de pagamento. Olhando a api não me parece que foi implementado um callback de error. 

Vocês poderiam adicionar um callback de falha de pagamento para que seja possível capturar um erro?

Api: https://assets.pagar.me/checkout/checkout.js

**Comment by thiagommedeiros** [comment]
@raphaelmonteiro Estamos trabalhando nesse problema para lançar a correção antes da Black Friday, então esse `callback de erro` já está no nosso roadmap.

Assim que isso for lançado nossa equipe de Relacionamento entrará em contato para informar.

Obrigado pela contribuição! Abs! =)

**Comment by MarcoWorms** [comment]
Como ja foi respondido vou fechar aqui, se tiver alguma outra dúvida e só reabrir @raphaelmonteiro  :)
