### ISSUE TITLE
Adicionar .babelrc para o .npmignore

### ISSUE THREAD

**Issue by celso-henrique** [pagarme/pagarme-js#82]
Ao fazer upgrade para o babel 6, o babel começa a considerar os arquivos .babelrc dentro da pasta node_modules, fazendo com que aplicações tenham problemas, como por exemplo ao usar o pagarmejs no React Native.

Discussão sobre:
 facebook/react-native#4062

Seria interessante adicionar o arquivo .babelrc ao .npmignore para manter a consistência em aplicações usando babel 6.

**Comment by MarcoWorms** [comment]
Opa, legal saber disso! Quer mandar esse PR pra nós? ;)

**Comment by celso-henrique** [comment]
Pronto, qualquer coisa to aqui 👍 
#84

**Comment by derekstavis** [comment]
Opa @celso-henrique, muitíssimo obrigado pelo PR! Logo que tivermos uma release pingamos você. Vamos ver se conseguimos fazer uma release com o #81 e seu PR juntos :)

**Comment by MarcoWorms** [comment]
https://github.com/pagarme/pagarme-js/pull/84
