### ISSUE TITLE
Safari can't open assets.pagar.me

### ISSUE THREAD

**Issue by murilohns** [pagarme/pagarme-js#92]
## Description

When i try to access https://assets.pagar.me occurs:
![image](https://user-images.githubusercontent.com/18074134/31227795-960f5502-a9b1-11e7-80e5-82e2b6bbd215.png)

## My Setup
- Operating System: Windows

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

### Current Behavior
![image](https://user-images.githubusercontent.com/18074134/31227811-a3b16a4c-a9b1-11e7-8b23-28721c537b4d.png)

### Expected Behavior

![image](https://user-images.githubusercontent.com/18074134/31227835-b60c20d8-a9b1-11e7-8701-3d8541d36a3b.png)

**Comment by wilkmaia** [comment]
Não é um problema relacionado à biblioteca. Estamos investigando em outra esfera.
