### ISSUE TITLE
Internet explorer doesn't support Object.assign

### ISSUE THREAD

**Issue by murilohns** [pagarme/pagarme-js#95]
## Description
Internet explorer doesn't support Object.assign, in this line:
https://github.com/pagarme/pagarme-js/blob/master/lib/index.js#L6

We can see the compatibility in https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign#Browser_compatibility

## My Setup
- Windows 10
- Internet Explorer 11

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

### Current Behavior

![image](https://user-images.githubusercontent.com/18074134/31608379-ed1758a4-b24e-11e7-9ac7-e1164fd8abad.png)

**Comment by MarcoWorms** [comment]
Thanks! Just opened #97 replacing it with ramda's merge :)
